// Auto-generated by @lionden/leo-compiler — do not edit
// Program: record_output_matcher.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// RecordOutputMatcher contract wrapper
// ---------------------------------------------------------------------------

export class RecordOutputMatcher extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("record_output_matcher.aleo", options);
  }

  readonly identity = {
    locally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      const _result = await this.executeLocal("identity", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "identity", 0));
    },

    failsLocally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      await this.expectLocalFailure("identity", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      return this.expectLocalFailure("identity", _args, options ?? {});
    },

    submitted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      return this.submitTransition("identity", _args, options ?? {});
    },

    settled: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      return this.settleTyped("identity", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "record_output_matcher.aleo", "identity", 0), tpk, "record_output_matcher.aleo", "identity", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      return this.expectAcceptedTyped("identity", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "record_output_matcher.aleo", "identity", 0), tpk, "record_output_matcher.aleo", "identity", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("identity", "a")),
      ];
      return this.expectRejected("identity", _args, options ?? {});
    },
  } as const;
}

export function createRecordOutputMatcher(options?: BaseContractOptions): RecordOutputMatcher {
  return new RecordOutputMatcher(options);
}
