// Auto-generated by @lionden/leo-compiler — do not edit
// Program: base_struct_holder.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface BaseContract {
  readonly x: number;
}

export interface BaseContractInput {
  readonly x: number;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeBaseContract(value: BaseContractInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("x: " + BaseContract.serializeUInt(value.x, 32, BaseContract.childInputContext(context, "x")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeBaseContract(value: string): BaseContract {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
  };
}

// ---------------------------------------------------------------------------
// BaseStructHolder contract wrapper
// ---------------------------------------------------------------------------

export class BaseStructHolder extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("base_struct_holder.aleo", options);
  }

  readonly use_it = {
    locally: async (args: { readonly a: BaseContractInput }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      const _result = await this.executeLocal("use_it", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "use_it", 0));
    },

    failsLocally: async (args: { readonly a: BaseContractInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      await this.expectLocalFailure("use_it", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: BaseContractInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      return this.expectLocalFailure("use_it", _args, options ?? {});
    },

    submitted: async (args: { readonly a: BaseContractInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      return this.submitTransition("use_it", _args, options ?? {});
    },

    settled: async (args: { readonly a: BaseContractInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      return this.settleTyped("use_it", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "base_struct_holder.aleo", "use_it", 0), tpk, "base_struct_holder.aleo", "use_it", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: BaseContractInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      return this.expectAcceptedTyped("use_it", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "base_struct_holder.aleo", "use_it", 0), tpk, "base_struct_holder.aleo", "use_it", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: BaseContractInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeBaseContract(args.a as BaseContractInput, this.inputContext("use_it", "a")),
      ];
      return this.expectRejected("use_it", _args, options ?? {});
    },
  } as const;
}

export function createBaseStructHolder(options?: BaseContractOptions): BaseStructHolder {
  return new BaseStructHolder(options);
}
