import { defineConfig } from "@lionden/config";
import pluginDeploy from "@lionden/plugin-deploy";
import pluginLeo from "@lionden/plugin-leo";
import pluginNetwork from "@lionden/plugin-network";
import pluginTest from "@lionden/plugin-test";

/**
 * Tier 4 scale fixture. Not an example and not part of any smoke lane — it
 * exists only for `scripts/verify-deploy-scale.mjs`, which is the acceptance
 * test for the Leo deploy backend's reason to exist.
 *
 * The programs under `programs/` are generated by `scripts/gen-large-program.mjs`:
 * four heavy libraries plus a thin `scale_probe.aleo` that imports all four.
 * Each library is comfortably under snarkVM's 2,097,152-variable per-program
 * cap, but deploying the probe re-synthesizes a key for every function it calls
 * across the closure, and that sum is what the SDK cannot fit. See the
 * measurement tables in the generator.
 *
 * `ephemeral: false` so a real record is written and success can be checked
 * from disk rather than inferred from an exit code.
 */
export default defineConfig({
  plugins: [pluginLeo, pluginNetwork, pluginDeploy, pluginTest],
  leoVersion: "4.3.2",
  defaultNetwork: "devnode",
  networks: {
    devnode: { type: "devnode", autoBlock: true },
  },
  deploy: {
    ephemeral: false,
    confirmTransactions: true,
    // Key synthesis across a closure this large is the slow part, and the whole
    // point of the Leo backend is that it survives long runs and resumes from
    // `~/.aleo`. The default 30 minutes is not obviously enough here.
    leo: { timeout: 3_600_000 },
  },
});
