import { describe, it, beforeAll, afterAll } from "vitest";
import {
  setup,
  loadFixture,
  clearFixtures,
  type TestContext,
  assertMappingValue,
} from "@lionden/testing";

// TypeScript bindings — generated by `lionden compile` before tests run.
// This is the first example that uses typechain in tests.
import { createEscrow } from "../typechain/Escrow.js";

async function deployEscrow() {
  const ctx = await setup();
  try {
    await ctx.deploy("escrow", { noCompile: true });
    return { ctx };
  } catch (error) {
    await ctx.teardown();
    throw error;
  }
}

let ctx: TestContext | undefined;

beforeAll(async () => {
  const fixture = await loadFixture(deployEscrow);
  ctx = fixture.ctx;
});

afterAll(async () => {
  if (ctx) {
    await ctx.teardown();
  } else {
    clearFixtures();
  }
});

describe("escrow program (via typechain)", () => {
  const escrow = createEscrow();

  beforeAll(() => {
    escrow.connect(ctx!.lre);
  });

  describe("create_escrow", () => {
    it("creates an escrow with status 0", async () => {
      await escrow.create_escrowBroadcast(42n);

      await assertMappingValue(
        ctx!.connection,
        "escrow.aleo",
        "escrow_status",
        "42u64",
        "0u8",
      );
    });
  });

  describe("fund_escrow", () => {
    it("funds the escrow and transitions status to 1", async () => {
      await escrow.fund_escrowBroadcast(42n);

      await assertMappingValue(
        ctx!.connection,
        "escrow.aleo",
        "escrow_status",
        "42u64",
        "1u8",
      );
    });
  });

  describe("complete_escrow", () => {
    it("completes the escrow and transitions status to 2", async () => {
      await escrow.complete_escrowBroadcast(42n);

      await assertMappingValue(
        ctx!.connection,
        "escrow.aleo",
        "escrow_status",
        "42u64",
        "2u8",
      );
    });
  });
});
