// Auto-generated by @lionden/leo-compiler — do not edit
// Program: token_registry.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Token {
  readonly owner: LeoAddress;
  readonly amount: bigint;
  readonly _nonce: LeoGroup;
}

export interface TokenInput {
  readonly owner: AddressInput;
  readonly amount: bigint;
  readonly _nonce: GroupInput;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeToken(value: TokenInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];
  if (typeof _raw === "string") return _raw;
  const fields: string[] = [];
  fields.push("owner: " + BaseContract.serializeAddress(value.owner, BaseContract.childInputContext(context, "owner")));
  fields.push("amount: " + BaseContract.serializeUInt(value.amount, 64, BaseContract.childInputContext(context, "amount")));
  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeToken(value: string): Token {
  const _fields = BaseContract.parseStruct(value);
  const _record: Token = {
    owner: BaseContract.parseAddress(_fields["owner"]!),
    amount: BaseContract.parseBigInt(_fields["amount"]!),
    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),
  };
  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });
  return _record;
}

export async function decryptToken(ciphertext: string, key: RecordDecryptionKey): Promise<Token> {
  return BaseContract.decryptRecord(ciphertext, key, deserializeToken);
}

// ---------------------------------------------------------------------------
// TokenRegistry contract wrapper
// ---------------------------------------------------------------------------

export class TokenRegistry extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("token_registry.aleo", options);
  }

  readonly mint = {
    locally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<Token> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      const _result = await this.executeLocal("mint", _args, options ?? {});
      return deserializeToken(this.outputAt(_result, "mint", 0));
    },

    failsLocally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      await this.expectLocalFailure("mint", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      return this.expectLocalFailure("mint", _args, options ?? {});
    },

    submitted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      return this.submitTransition("mint", _args, options ?? {});
    },

    settled: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      return this.settleTyped("mint", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedRecord("token_registry.aleo", "Token", BaseContract.rawOutputAt(rawOutputs, "token_registry.aleo", "mint", 0), deserializeToken));
    },

    accepted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      return this.expectAcceptedTyped("mint", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedRecord("token_registry.aleo", "Token", BaseContract.rawOutputAt(rawOutputs, "token_registry.aleo", "mint", 0), deserializeToken));
    },

    rejected: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint", "amount")),
      ];
      return this.expectRejected("mint", _args, options ?? {});
    },
  } as const;
}

export function createTokenRegistry(options?: BaseContractOptions): TokenRegistry {
  return new TokenRegistry(options);
}
