// Auto-generated by @lionden/leo-compiler — do not edit
// Program: member_collisions.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// MemberCollisions contract wrapper
// ---------------------------------------------------------------------------

export class MemberCollisions extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("member_collisions.aleo", options);
  }

  readonly connect = {
    locally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      const _result = await this.executeLocal("connect", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "connect", 0));
    },

    failsLocally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      await this.expectLocalFailure("connect", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      return this.expectLocalFailure("connect", _args, options ?? {});
    },

    submitted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      return this.submitTransition("connect", _args, options ?? {});
    },

    settled: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      return this.settleTyped("connect", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "connect", 0), tpk, "member_collisions.aleo", "connect", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      return this.expectAcceptedTyped("connect", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "connect", 0), tpk, "member_collisions.aleo", "connect", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("connect", "a")),
      ];
      return this.expectRejected("connect", _args, options ?? {});
    },
  } as const;

  readonly withSigner = {
    locally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      const _result = await this.executeLocal("withSigner", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "withSigner", 0));
    },

    failsLocally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      await this.expectLocalFailure("withSigner", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      return this.expectLocalFailure("withSigner", _args, options ?? {});
    },

    submitted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      return this.submitTransition("withSigner", _args, options ?? {});
    },

    settled: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      return this.settleTyped("withSigner", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "withSigner", 0), tpk, "member_collisions.aleo", "withSigner", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      return this.expectAcceptedTyped("withSigner", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "withSigner", 0), tpk, "member_collisions.aleo", "withSigner", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("withSigner", "a")),
      ];
      return this.expectRejected("withSigner", _args, options ?? {});
    },
  } as const;

  readonly programId = {
    locally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      const _result = await this.executeLocal("programId", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "programId", 0));
    },

    failsLocally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      await this.expectLocalFailure("programId", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      return this.expectLocalFailure("programId", _args, options ?? {});
    },

    submitted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      return this.submitTransition("programId", _args, options ?? {});
    },

    settled: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      return this.settleTyped("programId", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "programId", 0), tpk, "member_collisions.aleo", "programId", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      return this.expectAcceptedTyped("programId", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "programId", 0), tpk, "member_collisions.aleo", "programId", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("programId", "a")),
      ];
      return this.expectRejected("programId", _args, options ?? {});
    },
  } as const;

  readonly mappings = {
    locally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<number> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      const _result = await this.executeLocal("mappings", _args, options ?? {});
      return BaseContract.parseNumber(this.outputAt(_result, "mappings", 0));
    },

    failsLocally: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      await this.expectLocalFailure("mappings", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly a: number }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      return this.expectLocalFailure("mappings", _args, options ?? {});
    },

    submitted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      return this.submitTransition("mappings", _args, options ?? {});
    },

    settled: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      return this.settleTyped("mappings", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "mappings", 0), tpk, "member_collisions.aleo", "mappings", 1, BaseContract.parseNumber));
    },

    accepted: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<number>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      return this.expectAcceptedTyped("mappings", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "member_collisions.aleo", "mappings", 0), tpk, "member_collisions.aleo", "mappings", 1, BaseContract.parseNumber));
    },

    rejected: async (args: { readonly a: number }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.a, 32, this.inputContext("mappings", "a")),
      ];
      return this.expectRejected("mappings", _args, options ?? {});
    },
  } as const;

  readonly bump = {
    locally: async (args: { readonly who: AddressInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      const _result = await this.executeLocal("bump", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly who: AddressInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      await this.expectLocalFailure("bump", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly who: AddressInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      return this.expectLocalFailure("bump", _args, options ?? {});
    },

    submitted: async (args: { readonly who: AddressInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      return this.submitTransition("bump", _args, options ?? {});
    },

    settled: async (args: { readonly who: AddressInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      return this.settleTyped("bump", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => undefined as void);
    },

    accepted: async (args: { readonly who: AddressInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      return this.expectAcceptedTyped("bump", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => undefined as void);
    },

    rejected: async (args: { readonly who: AddressInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.who, this.inputContext("bump", "who")),
      ];
      return this.expectRejected("bump", _args, options ?? {});
    },
  } as const;

  readonly mappings = {
    counts: {
      contains: async (key: AddressInput): Promise<boolean> => {
        return this.mappingContains("counts", BaseContract.serializeAddress(key, { programId: this.programId, input: "counts key" }));
      },
      get: async (key: AddressInput): Promise<bigint> => {
        const _result = await this.requireMappingRaw("counts", BaseContract.serializeAddress(key, { programId: this.programId, input: "counts key" }));
        return BaseContract.parseBigInt(_result);
      },
      getOrUse: async (key: AddressInput, def: bigint): Promise<bigint> => {
        const _result = await this.queryMapping("counts", BaseContract.serializeAddress(key, { programId: this.programId, input: "counts key" }));
        if (_result === null) return def;
        return BaseContract.parseBigInt(_result);
      },
      tryGet: async (key: AddressInput): Promise<bigint | null> => {
        const _result = await this.queryMapping("counts", BaseContract.serializeAddress(key, { programId: this.programId, input: "counts key" }));
        if (_result === null) return null;
        return BaseContract.parseBigInt(_result);
      },
    },
  } as const;
}

export function createMemberCollisions(options?: BaseContractOptions): MemberCollisions {
  return new MemberCollisions(options);
}
