import type {
  ProgramABI,
  StructABI,
  RecordABI,
  TransitionABI,
  MappingABI,
  StorageVariableABI,
  StorageType,
  AbiInput,
  AbiOutput,
  AleoType,
  PlaintextType,
  PrimitiveType,
  StructRef,
  RecordRef,
} from "../abi-types.js";
import {
  isBigIntType,
  structRefName,
  recordRefName,
  pathToTsName,
} from "./type-mapper.js";
import { CONTRACT_WRAPPER_TEMPLATE } from "./contract-wrapper.js";

/**
 * Generate TypeScript bindings from a ProgramABI.
 * Produces a single .ts file with:
 * - Struct/record interfaces
 * - Storage variable interface
 * - Serializer/deserializer functions
 * - Typed contract wrapper class
 */
export function generateBindings(abi: ProgramABI, allAbis: readonly ProgramABI[] = [abi]): string {
  const lines: string[] = [];
  const className = resolveClassName(abi);
  const ctx = createGenerationContext(abi, allAbis);

  lines.push("// Auto-generated by @lionden/leo-compiler — do not edit");
  lines.push(`// Program: ${abi.program}`);
  lines.push("");
  lines.push(
    'import { BaseContract, type AddressInput, type DynamicRecordInput, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";',
  );
  lines.push(...generateExternalImports(ctx));
  lines.push("");

  for (const struct of abi.structs) {
    lines.push(...generateStructInterface(struct, ctx));
    lines.push("");
  }

  for (const record of abi.records) {
    lines.push(...generateRecordInterface(record, ctx));
    lines.push("");
  }

  if (abi.storage_variables.length > 0) {
    lines.push(...generateStorageInterface(className, abi.storage_variables, ctx));
    lines.push("");
  }

  if (abi.structs.length > 0 || abi.records.length > 0) {
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("// Serialization / deserialization helpers");
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("");

    for (const struct of abi.structs) {
      lines.push(...generateStructSerializer(struct, ctx));
      lines.push("");
      lines.push(...generateStructDeserializer(struct, ctx));
      lines.push("");
    }

    for (const record of abi.records) {
      lines.push(...generateRecordSerializer(record, ctx));
      lines.push("");
      lines.push(...generateRecordDeserializer(record, ctx));
      lines.push("");
      lines.push(...generateRecordDecryptor(record));
      lines.push("");
    }
  }

  lines.push("// ---------------------------------------------------------------------------");
  lines.push(`// ${className} contract wrapper`);
  lines.push("// ---------------------------------------------------------------------------");
  lines.push("");
  lines.push(...generateContractClass(abi, className, ctx));

  return lines.join("\n") + "\n";
}

/**
 * Generate the BaseContract file content.
 */
export function generateBaseContract(): string {
  return CONTRACT_WRAPPER_TEMPLATE;
}

interface GenerationContext {
  readonly programId: string;
  readonly programsById: ReadonlyMap<string, ProgramABI>;
  readonly structsByKey: ReadonlyMap<string, StructABI>;
  readonly recordsByKey: ReadonlyMap<string, RecordABI>;
  readonly externalStructRefs: ReadonlyMap<string, StructRef>;
  readonly externalRecordRefs: ReadonlyMap<string, RecordRef>;
}

function createGenerationContext(abi: ProgramABI, allAbis: readonly ProgramABI[]): GenerationContext {
  const programsById = new Map<string, ProgramABI>();
  for (const programAbi of allAbis) {
    programsById.set(programAbi.program, programAbi);
  }
  programsById.set(abi.program, abi);

  const externalStructRefs = new Map<string, StructRef>();
  const externalRecordRefs = new Map<string, RecordRef>();
  collectExternalRefs(abi, programsById, externalStructRefs, externalRecordRefs);

  return {
    programId: abi.program,
    programsById,
    structsByKey: new Map(abi.structs.map((struct) => [pathKey(struct.path), struct])),
    recordsByKey: new Map(abi.records.map((record) => [pathKey(record.path), record])),
    externalStructRefs,
    externalRecordRefs,
  };
}

function collectExternalRefs(
  abi: ProgramABI,
  programsById: ReadonlyMap<string, ProgramABI>,
  structs: Map<string, StructRef>,
  records: Map<string, RecordRef>,
): void {
  const addStruct = (ref: StructRef): void => {
    if (!ref.program || ref.program === abi.program) return;
    const programAbi = programsById.get(ref.program);
    if (!programAbi?.structs.some((struct) => pathKey(struct.path) === pathKey(ref.path))) return;
    structs.set(externalRefKey(ref), ref);
  };

  const addRecord = (ref: RecordRef): void => {
    if (!ref.program || ref.program === abi.program) return;
    const programAbi = programsById.get(ref.program);
    if (!programAbi?.records.some((record) => pathKey(record.path) === pathKey(ref.path))) return;
    records.set(externalRefKey(ref), ref);
  };

  const visitPlaintext = (ty: PlaintextType): void => {
    if ("Struct" in ty) {
      addStruct(ty.Struct);
      return;
    }
    if ("Array" in ty) {
      visitPlaintext(ty.Array[0]);
      return;
    }
    if ("Optional" in ty) {
      visitPlaintext(ty.Optional);
    }
  };

  const visitAleo = (ty: AleoType): void => {
    if (ty === "DynamicRecord") return;
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext);
      return;
    }
    if ("Record" in ty) {
      addRecord(ty.Record);
    }
  };

  const visitStorage = (ty: StorageType): void => {
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext);
      return;
    }
    if ("Vector" in ty) {
      visitStorage(ty.Vector);
    }
  };

  for (const struct of abi.structs) {
    for (const field of struct.fields) visitPlaintext(field.ty);
  }
  for (const record of abi.records) {
    for (const field of record.fields) visitPlaintext(field.ty);
  }
  for (const mapping of abi.mappings) {
    visitPlaintext(mapping.key);
    visitPlaintext(mapping.value);
  }
  for (const variable of abi.storage_variables) visitStorage(variable.ty);
  for (const transition of abi.transitions) {
    for (const input of transition.inputs) visitAleo(input.ty);
    for (const output of transition.outputs) visitAleo(output.ty);
  }
}

// ---------------------------------------------------------------------------
// Struct/Record/Storage interface generation
// ---------------------------------------------------------------------------

function generateStructInterface(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  for (const field of struct.fields) {
    lines.push(`  readonly ${field.name}: ${plaintextToOutputBindingTs(field.ty, ctx)};`);
  }
  lines.push("}");
  return lines;
}

function generateRecordInterface(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  lines.push("  readonly owner: LeoAddress;");
  for (const field of record.fields) {
    if (field.name === "owner") continue;
    lines.push(`  readonly ${field.name}: ${plaintextToOutputBindingTs(field.ty, ctx)};`);
  }
  lines.push("  readonly _nonce: LeoGroup;");
  lines.push("}");
  return lines;
}

function generateStorageInterface(
  className: string,
  storageVariables: readonly StorageVariableABI[],
  ctx: GenerationContext,
): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${className}Storage {`);
  for (const variable of storageVariables) {
    lines.push(`  readonly ${variable.name}: ${storageTypeToBindingTs(variable.ty, ctx)};`);
  }
  lines.push("}");
  return lines;
}

// ---------------------------------------------------------------------------
// Serialization helpers
// ---------------------------------------------------------------------------

function generateStructSerializer(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const lines: string[] = [];
  lines.push(`export function serialize${name}(value: ${name}, context?: TransitionInputContext): string {`);
  lines.push("  BaseContract.assertObject(value, context);");
  lines.push("  const fields: string[] = [];");

  for (const field of struct.fields) {
    const serialized = serializePlaintextExpr(
      `value.${field.name}`,
      field.ty,
      ctx,
      `BaseContract.childInputContext(context, "${field.name}")`,
    );
    lines.push(`  fields.push("${field.name}: " + ${serialized});`);
  }

  lines.push('  return "{ " + fields.join(", ") + " }";');
  lines.push("}");
  return lines;
}

function generateRecordSerializer(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const lines: string[] = [];
  lines.push(`export function serialize${name}(value: ${name}, context?: TransitionInputContext): string {`);
  lines.push("  BaseContract.assertObject(value, context);");
  // Round-trip a record returned by a previous transition by replaying the
  // original literal verbatim. Without this, per-field visibility suffixes
  // mismatch on re-serialization and the runtime rejects the input. See
  // BaseContract.RECORD_RAW.
  lines.push("  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];");
  lines.push("  if (typeof _raw === \"string\") return _raw;");
  lines.push("  const fields: string[] = [];");

  for (const field of record.fields) {
    const serialized = serializePlaintextExpr(
      `value.${field.name}`,
      field.ty,
      ctx,
      `BaseContract.childInputContext(context, "${field.name}")`,
    );
    lines.push(`  fields.push("${field.name}: " + ${serialized});`);
  }
  lines.push('  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));');

  lines.push('  return "{ " + fields.join(", ") + " }";');
  lines.push("}");
  return lines;
}

function generateStructDeserializer(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const lines: string[] = [];
  lines.push(`export function deserialize${name}(value: string): ${name} {`);
  lines.push("  const _fields = BaseContract.parseStruct(value);");
  lines.push("  return {");
  for (const field of struct.fields) {
    lines.push(
      `    ${field.name}: ${deserializePlaintextExpr(`_fields["${field.name}"]!`, field.ty, ctx)},`,
    );
  }
  lines.push("  };");
  lines.push("}");
  return lines;
}

function generateRecordDecryptor(record: RecordABI): string[] {
  const name = pathToTsName(record.path);
  return [
    `export async function decrypt${name}(ciphertext: string, key: RecordDecryptionKey): Promise<${name}> {`,
    `  return BaseContract.decryptRecord(ciphertext, key, deserialize${name});`,
    "}",
  ];
}

function generateRecordDeserializer(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const lines: string[] = [];
  lines.push(`export function deserialize${name}(value: string): ${name} {`);
  lines.push("  const _fields = BaseContract.parseStruct(value);");
  lines.push(`  const _record: ${name} = {`);
  lines.push('    owner: BaseContract.parseAddress(_fields["owner"]!),');
  for (const field of record.fields) {
    if (field.name === "owner") continue;
    lines.push(
      `    ${field.name}: ${deserializePlaintextExpr(`_fields["${field.name}"]!`, field.ty, ctx)},`,
    );
  }
  lines.push('    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),');
  lines.push("  };");
  // Stash the original literal so serialize${name} can replay it verbatim
  // and avoid mangling per-field visibility suffixes on round-trip.
  lines.push(
    "  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });",
  );
  lines.push("  return _record;");
  lines.push("}");
  return lines;
}

// ---------------------------------------------------------------------------
// Contract class generation
// ---------------------------------------------------------------------------

function generateContractClass(
  abi: ProgramABI,
  className: string,
  ctx: GenerationContext,
): string[] {
  const lines: string[] = [];

  lines.push(`export class ${className} extends BaseContract {`);
  lines.push("  constructor() {");
  lines.push(`    super("${abi.program}");`);
  lines.push("  }");

  for (const transition of abi.transitions) {
    lines.push("");
    lines.push(...indentLines(generateTransitionMethod(transition, ctx), "  "));
  }

  for (const mapping of abi.mappings) {
    lines.push("");
    lines.push(...indentLines(generateMappingAccessor(mapping, ctx), "  "));
  }

  lines.push("}");
  lines.push("");
  lines.push(`export function create${className}(): ${className} {`);
  lines.push(`  return new ${className}();`);
  lines.push("}");

  return lines;
}

function generateTransitionMethod(
  transition: TransitionABI,
  ctx: GenerationContext,
): string[] {
  const lines: string[] = [];
  const hasInputs = transition.inputs.length > 0;
  const argsType = formatArgsObjectType(transition.inputs, ctx);
  const returnType = formatReturnType(transition.outputs, ctx);

  lines.push(`readonly ${transition.name} = {`);
  lines.push(`  locally: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<${returnType}> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    const _result = await this.executeLocal("${transition.name}", _args, options ?? {});`);

  if (transition.outputs.length === 1) {
    const output = transition.outputs[0]!;
    lines.push(`    return ${deserializeOutputExpr(`this.outputAt(_result, "${transition.name}", 0)`, output.ty, ctx)};`);
  } else if (transition.outputs.length > 1) {
    const tupleType = formatReturnType(transition.outputs, ctx);
    const elems = transition.outputs.map((o, i) =>
      deserializeOutputExpr(`this.outputAt(_result, "${transition.name}", ${i})`, o.ty, ctx),
    );
    lines.push(`    const _decoded: ${tupleType} = [${elems.join(", ")}];`);
    lines.push("    return _decoded;");
  } else {
    lines.push("    return undefined as any;");
  }

  lines.push("  },");
  lines.push("");
  lines.push(`  failsLocally: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<void> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    await this.expectLocalFailure("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(`  captureLocalFailure: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<LocalTransitionError> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.expectLocalFailure("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(`  submitted: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<SubmittedTransition> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.submitTransition("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(`  settled: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<SettledTransition> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.settleTransition("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(`  accepted: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<SettledTransition> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.expectAccepted("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(`  rejected: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<SettledTransition> => {`);
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.expectRejected("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("} as const;");

  return lines;
}

function generateSerializedArgsLines(
  transition: TransitionABI,
  ctx: GenerationContext,
  indent: string,
): string[] {
  const lines = [`${indent}const _args: string[] = [`];
  for (const input of transition.inputs) {
    lines.push(`${indent}  ${serializeInputExpr(input, transition.name, ctx)},`);
  }
  lines.push(`${indent}];`);
  return lines;
}

function generateMappingAccessor(
  mapping: MappingABI,
  ctx: GenerationContext,
): string[] {
  const keyType = plaintextToInputBindingTs(mapping.key, ctx);
  const valueType = plaintextToOutputBindingTs(mapping.value, ctx);
  const keySerializer = serializePlaintextExpr(
    "key",
    mapping.key,
    ctx,
    `{ programId: this.programId, input: "${mapping.name} key" }`,
  );
  const valueDeserializer = deserializePlaintextExpr("_result", mapping.value, ctx);

  return [
    `async get${capitalize(mapping.name)}(key: ${keyType}): Promise<${valueType} | null> {`,
    `  const _result = await this.queryMapping("${mapping.name}", ${keySerializer});`,
    "  if (_result === null) return null;",
    `  return ${valueDeserializer};`,
    "}",
  ];
}

// ---------------------------------------------------------------------------
// Type mapping helpers used by code generation
// ---------------------------------------------------------------------------

function plaintextToOutputBindingTs(pt: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in pt) return primitiveOutputBindingTs(pt.Primitive);
  if ("Struct" in pt) {
    if (isLocalStructRef(pt.Struct, ctx)) return structRefName(pt.Struct);
    const external = externalStructInfo(pt.Struct, ctx);
    return external?.typeName ?? "LeoPlaintext";
  }
  if ("Array" in pt) {
    const [elemType] = pt.Array;
    return `ReadonlyArray<${plaintextToOutputBindingTs(elemType, ctx)}>`;
  }
  if ("Optional" in pt) return `${plaintextToOutputBindingTs(pt.Optional, ctx)} | null`;
  return "unknown";
}

function plaintextToInputBindingTs(pt: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in pt) return primitiveInputBindingTs(pt.Primitive);
  if ("Struct" in pt) {
    if (isLocalStructRef(pt.Struct, ctx)) return structRefName(pt.Struct);
    const external = externalStructInfo(pt.Struct, ctx);
    return external?.typeName ?? "PlaintextInput";
  }
  if ("Array" in pt) {
    const [elemType] = pt.Array;
    return `ReadonlyArray<${plaintextToInputBindingTs(elemType, ctx)}>`;
  }
  if ("Optional" in pt) return `${plaintextToInputBindingTs(pt.Optional, ctx)} | null`;
  return "unknown";
}

function aleoTypeToOutputBindingTs(ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return "LeoDynamicRecord";
  if ("Plaintext" in ty) return plaintextToOutputBindingTs(ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return recordRefName(ty.Record);
    const external = externalRecordInfo(ty.Record, ctx);
    return external?.typeName ?? "LeoDynamicRecord";
  }
  if ("Future" in ty) return "void";
  return "unknown";
}

function aleoTypeToInputBindingTs(ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return "DynamicRecordInput";
  if ("Plaintext" in ty) return plaintextToInputBindingTs(ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return recordRefName(ty.Record);
    const external = externalRecordInfo(ty.Record, ctx);
    return external?.typeName ?? "DynamicRecordInput";
  }
  if ("Future" in ty) return "void";
  return "unknown";
}

function storageTypeToBindingTs(ty: StorageType, ctx: GenerationContext): string {
  if ("Plaintext" in ty) return plaintextToOutputBindingTs(ty.Plaintext, ctx);
  if ("Vector" in ty) return `${storageTypeToBindingTs(ty.Vector, ctx)}[]`;
  return "unknown";
}

function primitiveOutputBindingTs(prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address": return "LeoAddress";
      case "Boolean": return "boolean";
      case "Field": return "LeoField";
      case "Group": return "LeoGroup";
      case "Identifier": return "LeoIdentifier";
      case "Scalar": return "LeoScalar";
    }
  }
  if (isBigIntType(prim)) return "bigint";
  return "number";
}

function primitiveInputBindingTs(prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address": return "AddressInput";
      case "Boolean": return "boolean";
      case "Field": return "FieldInput";
      case "Group": return "GroupInput";
      case "Identifier": return "IdentifierInput";
      case "Scalar": return "ScalarInput";
    }
  }
  if (isBigIntType(prim)) return "bigint";
  return "number";
}

// ---------------------------------------------------------------------------
// Serialization expression generators (JS value → Leo string)
// ---------------------------------------------------------------------------

function serializeInputExpr(input: AbiInput, transitionName: string, ctx: GenerationContext): string {
  return serializeAleoTypeExpr(
    `args.${input.name}`,
    input.ty,
    ctx,
    `this.inputContext("${transitionName}", "${input.name}")`,
  );
}

function serializeAleoTypeExpr(
  expr: string,
  ty: AleoType,
  ctx: GenerationContext,
  contextExpr = "undefined",
): string {
  if (ty === "DynamicRecord") return `BaseContract.serializeDynamicRecord(${expr}, ${contextExpr})`;
  if ("Plaintext" in ty) return serializePlaintextExpr(expr, ty.Plaintext, ctx, contextExpr);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) {
      const typeName = recordRefName(ty.Record);
      return `serialize${typeName}(${expr} as ${typeName}, ${contextExpr})`;
    }
    const external = externalRecordInfo(ty.Record, ctx);
    return external
      ? `${external.serializerName}(${expr} as ${external.typeName}, ${contextExpr})`
      : `BaseContract.serializeDynamicRecord(${expr}, ${contextExpr})`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

function serializePlaintextExpr(
  expr: string,
  ty: PlaintextType,
  ctx: GenerationContext,
  contextExpr = "undefined",
): string {
  if ("Primitive" in ty) return serializePrimitive(expr, ty.Primitive, contextExpr);
  if ("Struct" in ty) {
    if (isLocalStructRef(ty.Struct, ctx)) {
      const typeName = structRefName(ty.Struct);
      return `serialize${typeName}(${expr} as ${typeName}, ${contextExpr})`;
    }
    const external = externalStructInfo(ty.Struct, ctx);
    return external
      ? `${external.serializerName}(${expr} as ${external.typeName}, ${contextExpr})`
      : `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
  }
  if ("Array" in ty) {
    const [elemType] = ty.Array;
    const elemSer = serializePlaintextExpr("e", elemType, ctx, "context");
    return `BaseContract.serializeArray(${expr}, ${contextExpr}, (e: unknown, context: TransitionInputContext | undefined) => ${elemSer})`;
  }
  if ("Optional" in ty) {
    const innerSer = serializePlaintextExpr(expr, ty.Optional, ctx, contextExpr);
    const zero = zeroLeoValue(ty.Optional, ctx);
    if (zero !== null) {
      return `(${expr} != null ? "{ is_some: true, val: " + ${innerSer} + " }" : "{ is_some: false, val: ${zero} }")`;
    }
    return `(${expr} != null ? "{ is_some: true, val: " + ${innerSer} + " }" : BaseContract.serializeUnsupportedOptionalNone(${contextExpr}))`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

// ---------------------------------------------------------------------------
// Deserialization expression generators (Leo string → JS value)
// ---------------------------------------------------------------------------

function deserializeOutputExpr(expr: string, ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return `BaseContract.parseDynamicRecord(${expr})`;
  if ("Plaintext" in ty) return deserializePlaintextExpr(expr, ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return `deserialize${recordRefName(ty.Record)}(${expr})`;
    const external = externalRecordInfo(ty.Record, ctx);
    return external ? `${external.deserializerName}(${expr})` : `BaseContract.parseDynamicRecord(${expr})`;
  }
  if ("Future" in ty) return "undefined as any";
  return expr;
}

function deserializePlaintextExpr(expr: string, ty: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in ty) return deserializePrimitiveExpr(expr, ty.Primitive);
  if ("Struct" in ty) {
    if (isLocalStructRef(ty.Struct, ctx)) return `deserialize${structRefName(ty.Struct)}(${expr})`;
    const external = externalStructInfo(ty.Struct, ctx);
    return external ? `${external.deserializerName}(${expr})` : `BaseContract.parsePlaintext(${expr})`;
  }
  if ("Array" in ty) {
    const [elemType] = ty.Array;
    return `BaseContract.parseArray(${expr}).map((e: string) => ${deserializePlaintextExpr("e", elemType, ctx)})`;
  }
  if ("Optional" in ty) {
    return `(() => { const _opt = BaseContract.parseStruct(${expr}); return BaseContract.parseBoolean(_opt["is_some"]!) ? ${deserializePlaintextExpr('_opt["val"]!', ty.Optional, ctx)} : null; })()`;
  }
  return expr;
}

function deserializePrimitiveExpr(expr: string, prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return `BaseContract.parseAddress(${expr})`;
      case "Field":
        return `BaseContract.parseField(${expr})`;
      case "Group":
        return `BaseContract.parseGroup(${expr})`;
      case "Scalar":
        return `BaseContract.parseScalar(${expr})`;
      case "Identifier":
        return `BaseContract.parseIdentifier(${expr})`;
      case "Boolean":
        return `BaseContract.parseBoolean(${expr})`;
    }
    return expr;
  }
  if (typeof prim === "object" && prim !== null && ("UInt" in prim || "Int" in prim)) {
    if (isBigIntType(prim)) {
      return `BaseContract.parseBigInt(${expr})`;
    }
    return `BaseContract.parseNumber(${expr})`;
  }
  return expr;
}

function serializePrimitive(expr: string, prim: PrimitiveType, contextExpr = "undefined"): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return `BaseContract.serializeAddress(${expr}, ${contextExpr})`;
      case "Field":
        return `BaseContract.serializeField(${expr}, ${contextExpr})`;
      case "Group":
        return `BaseContract.serializeGroup(${expr}, ${contextExpr})`;
      case "Scalar":
        return `BaseContract.serializeScalar(${expr}, ${contextExpr})`;
      case "Identifier":
        return `BaseContract.serializeIdentifier(${expr}, ${contextExpr})`;
      case "Boolean":
        return `BaseContract.serializeBoolean(${expr}, ${contextExpr})`;
    }
    return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
  }

  if (typeof prim === "object" && prim !== null && "UInt" in prim) {
    const bits = Number(prim.UInt.slice(1));
    return `BaseContract.serializeUInt(${expr}, ${bits}, ${contextExpr})`;
  }
  if (typeof prim === "object" && prim !== null && "Int" in prim) {
    const bits = Number(prim.Int.slice(1));
    return `BaseContract.serializeInt(${expr}, ${bits}, ${contextExpr})`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

// ---------------------------------------------------------------------------
// Zero-value helpers (for Optional None serialization)
// ---------------------------------------------------------------------------

function zeroLeoValue(
  ty: PlaintextType,
  ctx: GenerationContext,
  seen: ReadonlySet<string> = new Set(),
): string | null {
  if ("Primitive" in ty) {
    const prim = ty.Primitive;
    if (typeof prim === "string") {
      switch (prim) {
        case "Address":
          return "aleo1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3ljyzc";
        case "Boolean":
          return "false";
        case "Field":
          return "0field";
        case "Group":
          return "0group";
        case "Identifier":
          // Leo has no canonical zero identifier; Optional::None ignores val.
          return "'lionden_zero'";
        case "Scalar":
          return "0scalar";
      }
      return null;
    }
    if (typeof prim === "object" && prim !== null && "UInt" in prim) return `0${prim.UInt.toLowerCase()}`;
    if (typeof prim === "object" && prim !== null && "Int" in prim) return `0${prim.Int.toLowerCase()}`;
  }

  if ("Array" in ty) {
    const [elemType, length] = ty.Array;
    const elemZero = zeroLeoValue(elemType, ctx, seen);
    if (elemZero === null) return null;
    return `[${Array.from({ length }, () => elemZero).join(", ")}]`;
  }

  if ("Optional" in ty) {
    const innerZero = zeroLeoValue(ty.Optional, ctx, seen);
    if (innerZero === null) return null;
    return `{ is_some: false, val: ${innerZero} }`;
  }

  if ("Struct" in ty) {
    if (!isLocalStructRef(ty.Struct, ctx)) return null;

    const key = pathKey(ty.Struct.path);
    if (seen.has(key)) return null;

    const struct = ctx.structsByKey.get(key);
    if (!struct) return null;

    const nextSeen = new Set(seen);
    nextSeen.add(key);

    const fieldValues: string[] = [];
    for (const field of struct.fields) {
      const fieldZero = zeroLeoValue(field.ty, ctx, nextSeen);
      if (fieldZero === null) return null;
      fieldValues.push(`${field.name}: ${fieldZero}`);
    }
    return `{ ${fieldValues.join(", ")} }`;
  }

  return null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface ExternalRefInfo {
  readonly programId: string;
  readonly className: string;
  readonly baseName: string;
  readonly typeName: string;
  readonly serializerName: string;
  readonly deserializerName: string;
}

function generateExternalImports(ctx: GenerationContext): string[] {
  const importsByProgram = new Map<string, Set<string>>();

  for (const ref of ctx.externalStructRefs.values()) {
    const info = externalStructInfo(ref, ctx);
    if (!info) continue;
    const imports = importsByProgram.get(info.programId) ?? new Set<string>();
    imports.add(`type ${info.baseName} as ${info.typeName}`);
    imports.add(`serialize${info.baseName} as ${info.serializerName}`);
    imports.add(`deserialize${info.baseName} as ${info.deserializerName}`);
    importsByProgram.set(info.programId, imports);
  }

  for (const ref of ctx.externalRecordRefs.values()) {
    const info = externalRecordInfo(ref, ctx);
    if (!info) continue;
    const imports = importsByProgram.get(info.programId) ?? new Set<string>();
    imports.add(`type ${info.baseName} as ${info.typeName}`);
    imports.add(`serialize${info.baseName} as ${info.serializerName}`);
    imports.add(`deserialize${info.baseName} as ${info.deserializerName}`);
    importsByProgram.set(info.programId, imports);
  }

  return [...importsByProgram.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([programId, imports]) =>
      `import { ${[...imports].sort().join(", ")} } from "./${programIdToClassName(programId)}.js";`,
    );
}

function isLocalStructRef(ref: StructRef, ctx: GenerationContext): boolean {
  if (ref.program !== null && ref.program !== ctx.programId) return false;
  return ctx.structsByKey.has(pathKey(ref.path));
}

function isLocalRecordRef(ref: RecordRef, ctx: GenerationContext): boolean {
  if (ref.program !== null && ref.program !== ctx.programId) return false;
  return ctx.recordsByKey.has(pathKey(ref.path));
}

function externalStructInfo(ref: StructRef, ctx: GenerationContext): ExternalRefInfo | null {
  const programId = ref.program;
  if (!programId || programId === ctx.programId) return null;

  const abi = ctx.programsById.get(programId);
  if (!abi?.structs.some((struct) => pathKey(struct.path) === pathKey(ref.path))) return null;

  return externalInfo(programId, structRefName(ref));
}

function externalRecordInfo(ref: RecordRef, ctx: GenerationContext): ExternalRefInfo | null {
  const programId = ref.program;
  if (!programId || programId === ctx.programId) return null;

  const abi = ctx.programsById.get(programId);
  if (!abi?.records.some((record) => pathKey(record.path) === pathKey(ref.path))) return null;

  return externalInfo(programId, recordRefName(ref));
}

function externalInfo(programId: string, baseName: string): ExternalRefInfo {
  const className = programIdToClassName(programId);
  const typeName = `${className}_${baseName}`;
  return {
    programId,
    className,
    baseName,
    typeName,
    serializerName: `serialize${typeName}`,
    deserializerName: `deserialize${typeName}`,
  };
}

function pathKey(path: readonly string[]): string {
  return path.join("::");
}

function externalRefKey(ref: StructRef | RecordRef): string {
  return `${ref.program ?? ""}:${pathKey(ref.path)}`;
}

function formatArgsObjectType(inputs: readonly AbiInput[], ctx: GenerationContext): string {
  const fields = inputs.map((input) =>
    `readonly ${input.name}: ${aleoTypeToInputBindingTs(input.ty, ctx)}`,
  );
  return `{ ${fields.join("; ")} }`;
}

function formatTransitionMethodParams(
  hasInputs: boolean,
  argsType: string,
  optionsType: "LocalExecutionOptions" | "OnChainExecutionOptions",
): string {
  return hasInputs ? `args: ${argsType}, options?: ${optionsType}` : `options?: ${optionsType}`;
}

function formatReturnType(outputs: readonly AbiOutput[], ctx: GenerationContext): string {
  if (outputs.length === 0) return "void";
  if (outputs.length === 1) return aleoTypeToOutputBindingTs(outputs[0]!.ty, ctx);
  return `[${outputs.map((o) => aleoTypeToOutputBindingTs(o.ty, ctx)).join(", ")}]`;
}

function programIdToClassName(programId: string): string {
  const name = programId.replace(/\.aleo$/, "");
  return name
    .split(/[_\-.]/)
    .map(capitalize)
    .join("");
}

/** Derive a class name that does not collide with struct/record interface names. */
function resolveClassName(abi: ProgramABI): string {
  const base = programIdToClassName(abi.program);
  const typeNames = new Set<string>([
    ...abi.structs.map((s) => pathToTsName(s.path)),
    ...abi.records.map((r) => pathToTsName(r.path)),
  ]);
  let candidate = base;
  while (typeNames.has(candidate)) {
    candidate += "Contract";
  }
  return candidate;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function indentLines(lines: readonly string[], indent: string): string[] {
  return lines.map((line) => line === "" ? "" : `${indent}${line}`);
}
