import type {
  AbiInput,
  AbiOutput,
  AleoType,
  MappingABI,
  PlaintextType,
  PrimitiveType,
  ProgramABI,
  RecordABI,
  RecordRef,
  StorageType,
  StorageVariableABI,
  StructABI,
  StructRef,
  TransitionABI,
} from "../abi-types.js";
import { CodegenError } from "./codegen-error.js";
import { CONTRACT_WRAPPER_TEMPLATE } from "./contract-wrapper.js";
import {
  disambiguateInputName,
  isBigIntType,
  pathToTsName,
  recordRefName,
  structRefName,
} from "./type-mapper.js";

/**
 * Options for `generateBindings`. Currently used to thread per-program
 * dynamic-record helper configuration through to the emitter; plugin-leo
 * filters the global helper map by ownership before passing here.
 */
export interface GenerateBindingsOptions {
  readonly dynamicRecords?: readonly ResolvedDynamicRecordHelperEmit[];
}

/**
 * Resolved helper entry as the emitter consumes it. `sourceProgram` is bound
 * to the owning programId by the time the emitter runs (plugin-leo's routing
 * step). Shape-equivalent to `ResolvedDynamicRecordHelper` from `@lionden/config`
 * but redeclared locally so the codegen layer doesn't depend on the config
 * package.
 */
export interface ResolvedDynamicRecordHelperEmit {
  readonly helperName: string;
  readonly sourceRecord: string;
  readonly sourceProgram: string;
  readonly schema: Readonly<Record<string, string>>;
}

const SUPPORTED_DYNAMIC_RECORD_PRIMITIVES = new Set<string>([
  "address",
  "boolean",
  "field",
  "group",
  "scalar",
  "u8",
  "u16",
  "u32",
  "u64",
  "u128",
  "i8",
  "i16",
  "i32",
  "i64",
  "i128",
]);

/**
 * Generate TypeScript bindings from a ProgramABI.
 * Produces a single .ts file with:
 * - Struct/record interfaces
 * - Storage variable interface
 * - Serializer/deserializer functions
 * - Typed contract wrapper class
 */
export function generateBindings(
  abi: ProgramABI,
  allAbis: readonly ProgramABI[] = [abi],
  options: GenerateBindingsOptions = {},
): string {
  const lines: string[] = [];

  const helpers = (options.dynamicRecords ?? []).filter(
    (helper) => helper.sourceProgram === abi.program,
  );
  const includeLeoValueImport = helpers.length > 0;
  const className = resolveContractClassName(abi, { includeLeoValueImport });

  // Helper names are module-level `export const`s; reserve them so derived
  // external aliases/value bindings (e.g. `GoldToken_Token`) bump away from a
  // helper that happens to share that name, instead of redeclaring it (TS2451).
  const ctx = createGenerationContext(
    abi,
    allAbis,
    helpers.map((helper) => helper.helperName),
    includeLeoValueImport,
  );
  assertCodegenSupportedTypes(abi);
  assertNoExecutableConstParameters(abi);
  assertNoReservedLocalTypeNames(abi);
  assertNoReservedContractMembers(abi);
  assertNoReservedHelperNames(
    abi,
    className,
    includeLeoValueImport,
    helpers,
    ctx.externalInfoByKey.values(),
  );

  const hasExternalRefs = ctx.externalStructRefs.size + ctx.externalRecordRefs.size > 0;

  lines.push("// Auto-generated by @lionden/leo-compiler — do not edit");
  lines.push(`// Program: ${abi.program}`);
  lines.push("");
  lines.push(
    baseContractImport(includeLeoValueImport, hasExternalRefs ? ctx.widenInputAlias : null),
  );
  lines.push(...generateExternalImports(ctx));
  lines.push("");

  for (const struct of abi.structs) {
    lines.push(...generateStructInterface(struct, ctx));
    lines.push("");
    lines.push(...generateStructInputInterface(struct, ctx));
    lines.push("");
  }

  for (const record of abi.records) {
    lines.push(...generateRecordInterface(record, ctx));
    lines.push("");
    lines.push(...generateRecordInputInterface(record, ctx));
    lines.push("");
  }

  if (abi.storage_variables.length > 0) {
    lines.push(...generateStorageInterface(className, abi.storage_variables, ctx));
    lines.push("");
  }

  if (abi.structs.length > 0 || abi.records.length > 0) {
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("// Serialization / deserialization helpers");
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("");

    for (const struct of abi.structs) {
      lines.push(...generateStructSerializer(struct, ctx));
      lines.push("");
      lines.push(...generateStructDeserializer(struct, ctx));
      lines.push("");
    }

    for (const record of abi.records) {
      lines.push(...generateRecordSerializer(record, ctx));
      lines.push("");
      lines.push(...generateRecordDeserializer(record, ctx));
      lines.push("");
      lines.push(...generateRecordDecryptor(record));
      lines.push("");
    }
  }

  if (helpers.length > 0) {
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("// Interface conversion helpers");
    lines.push("// ---------------------------------------------------------------------------");
    lines.push("");
    for (const helper of helpers) {
      lines.push(...generateDynamicRecordHelper(helper, abi, ctx));
      lines.push("");
    }
  }

  lines.push("// ---------------------------------------------------------------------------");
  lines.push(`// ${className} contract wrapper`);
  lines.push("// ---------------------------------------------------------------------------");
  lines.push("");
  lines.push(...generateContractClass(abi, className, ctx));

  return lines.join("\n") + "\n";
}

function assertNoExecutableConstParameters(abi: ProgramABI): void {
  for (const transition of abi.transitions) {
    if (transition.const_parameters && transition.const_parameters.length > 0) {
      throw new CodegenError(
        `Code generation for ${abi.program}/${transition.name} is unsupported: ` +
          "executable functions with const_parameters are not yet supported.",
        {
          programId: abi.program,
          phase: "generate",
        },
      );
    }
  }
}

function assertCodegenSupportedTypes(abi: ProgramABI): void {
  // Keep this allowlist in sync with the primitive branches that actually emit
  // bindings and serializer/parser calls below. The validation pass exists so
  // those lower-level helpers never fall through to unsafe generic codegen.
  const visitPrimitive = (prim: PrimitiveType, abiPath: string): void => {
    if (typeof prim === "string") {
      switch (prim) {
        case "Address":
        case "Boolean":
        case "Field":
        case "Group":
        case "Identifier":
        case "Scalar":
          return;
        default:
          throwUnsupportedPrimitive(abi.program, abiPath, prim);
      }
    }

    if (typeof prim === "object" && prim !== null) {
      if ("UInt" in prim) {
        switch (prim.UInt) {
          case "U8":
          case "U16":
          case "U32":
          case "U64":
          case "U128":
            return;
          default:
            throwUnsupportedPrimitive(abi.program, abiPath, `UInt(${String(prim.UInt)})`);
        }
      }
      if ("Int" in prim) {
        switch (prim.Int) {
          case "I8":
          case "I16":
          case "I32":
          case "I64":
          case "I128":
            return;
          default:
            throwUnsupportedPrimitive(abi.program, abiPath, `Int(${String(prim.Int)})`);
        }
      }
    }

    throwUnsupportedPrimitive(abi.program, abiPath, JSON.stringify(prim)!);
  };

  const visitPlaintext = (ty: PlaintextType, abiPath: string): void => {
    if ("Primitive" in ty) {
      visitPrimitive(ty.Primitive, `${abiPath}.Primitive`);
      return;
    }
    // Struct references are validated at their declaration site in the owning
    // program's generateBindings() call; unresolved external refs intentionally
    // remain dynamic/plaintext fallback surfaces.
    if ("Struct" in ty) return;
    if ("Array" in ty) {
      visitPlaintext(ty.Array[0], `${abiPath}.Array[0]`);
      return;
    }
    if ("Optional" in ty) {
      visitPlaintext(ty.Optional, `${abiPath}.Optional`);
    }
  };

  const visitAleo = (ty: AleoType, abiPath: string): void => {
    if (ty === "DynamicRecord") return;
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext, `${abiPath}.Plaintext`);
      return;
    }
    // Record references follow the same declaration-site validation contract
    // as struct references.
    if ("Record" in ty) return;
    if ("Future" in ty) return;
  };

  const visitStorage = (ty: StorageType, abiPath: string): void => {
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext, `${abiPath}.Plaintext`);
      return;
    }
    if ("Vector" in ty) {
      visitStorage(ty.Vector, `${abiPath}.Vector`);
    }
  };

  abi.structs.forEach((struct, structIndex) => {
    struct.fields.forEach((field, fieldIndex) => {
      visitPlaintext(field.ty, `structs[${structIndex}].fields[${fieldIndex}].ty`);
    });
  });

  abi.records.forEach((record, recordIndex) => {
    record.fields.forEach((field, fieldIndex) => {
      visitPlaintext(field.ty, `records[${recordIndex}].fields[${fieldIndex}].ty`);
    });
  });

  abi.mappings.forEach((mapping, mappingIndex) => {
    visitPlaintext(mapping.key, `mappings[${mappingIndex}].key`);
    visitPlaintext(mapping.value, `mappings[${mappingIndex}].value`);
  });

  abi.storage_variables.forEach((variable, variableIndex) => {
    visitStorage(variable.ty, `storage_variables[${variableIndex}].ty`);
  });

  abi.transitions.forEach((transition, transitionIndex) => {
    transition.inputs.forEach((input, inputIndex) => {
      visitAleo(input.ty, `transitions[${transitionIndex}].inputs[${inputIndex}].ty`);
    });
    transition.outputs.forEach((output, outputIndex) => {
      visitAleo(output.ty, `transitions[${transitionIndex}].outputs[${outputIndex}].ty`);
    });
  });
}

function throwUnsupportedPrimitive(programId: string, abiPath: string, primitive: string): never {
  throw new CodegenError(
    `Code generation for program ${programId} is unsupported at ABI path ${abiPath}: ` +
      `Primitive::${primitive} is not supported by generated bindings yet.`,
    {
      programId,
      abiPath,
      primitive,
      phase: "generate",
    },
  );
}

/**
 * Generate the BaseContract file content.
 */
export function generateBaseContract(): string {
  return CONTRACT_WRAPPER_TEMPLATE;
}

/**
 * Type-level bindings `baseContractImport` always imports from
 * `./BaseContract.js`, in the historically-emitted alphabetical order. Single
 * source of truth shared by `baseContractImport` (which prefixes each with
 * `type `) and `RESERVED_BASE_CONTRACT_TYPE_IMPORT_NAMES`, so the emitted import
 * list and the collision-guard list cannot drift apart.
 *
 * Excludes `BaseContract` (imported as a value, reserved separately) and
 * `WidenInput` (conditional + alias-aware, deliberately not reserved).
 */
const BASE_CONTRACT_TYPE_IMPORT_NAMES: readonly string[] = [
  "AcceptedTransition",
  "AddressInput",
  "BaseContractOptions",
  "CapturedRecord",
  "ConfirmedTransitionRecord",
  "DecryptionKey",
  "DynamicRecordInput",
  "EncryptedRecord",
  "EncryptedValue",
  "FieldInput",
  "GroupInput",
  "IdentifierInput",
  "IdOnlyDynamicRecordHandle",
  "IdOnlyExternalRecordHandle",
  "IdOnlyRecordSource",
  "LeoAddress",
  "LeoDynamicRecord",
  "LeoField",
  "LeoGroup",
  "LeoIdentifier",
  "LeoPlaintext",
  "LeoScalar",
  "LocalExecutionOptions",
  "LocalTransitionError",
  "OnChainExecutionOptions",
  "PlaintextInput",
  "RawTransitionOutput",
  "RecordDecryptionKey",
  "RecordOutputMatcher",
  "RejectedTransition",
  "ScalarInput",
  "SettledTransition",
  "SubmittedTransition",
  "TransitionInputContext",
];

/**
 * Build the fixed `import { … } from "./BaseContract.js"` line. `Leo` is added
 * only when the module emits dynamic-record helpers; `WidenInput` only when the
 * module has external struct/record refs (which alias to `WidenInput<…>`), and
 * under a collision-safe local name (`widenImport`, normally `"WidenInput"`).
 * The type list is alphabetical, matching the historically-emitted order so
 * modules without those features produce byte-identical imports.
 */
function baseContractImport(includeLeo: boolean, widenImport: string | null): string {
  const names: string[] = [
    "BaseContract",
    ...(includeLeo ? ["Leo"] : []),
    "createRecordOutputMatcher",
    ...BASE_CONTRACT_TYPE_IMPORT_NAMES.map((name) => `type ${name}`),
    ...(widenImport === null
      ? []
      : [widenImport === "WidenInput" ? "type WidenInput" : `type WidenInput as ${widenImport}`]),
  ];
  return `import { ${names.join(", ")} } from "./BaseContract.js";`;
}

const BASE_CONTRACT_VALUE_IMPORT_NAMES: readonly string[] = [
  "BaseContract",
  "createRecordOutputMatcher",
];

/**
 * Bare value-binding names introduced by `baseContractImport`. A generated
 * contract class or its `create${class}` factory must avoid these, but local
 * interfaces can coexist with value-only imports such as `Leo` and
 * `createRecordOutputMatcher`.
 */
function baseContractValueImportNames(includeLeo: boolean): readonly string[] {
  return includeLeo
    ? ["BaseContract", "Leo", "createRecordOutputMatcher"]
    : BASE_CONTRACT_VALUE_IMPORT_NAMES;
}

/**
 * Bare type-binding names introduced by `baseContractImport`. A local
 * struct/record interface whose name equals one of these collides with the
 * import (TS2440 / TS2300). Keep in sync with `baseContractImport`.
 *
 * `WidenInput` is deliberately excluded: it is the one fixed import that is
 * already alias-aware (`widenInputAlias` re-imports it as `WidenInput_` when a
 * local declaration shadows it), so a local `WidenInput` is handled, not
 * rejected.
 */
const RESERVED_BASE_CONTRACT_TYPE_IMPORT_NAMES: readonly string[] = [
  // `BaseContract` is imported as a value but is also usable as a type (a local
  // `interface BaseContract` collides with it), so reserve it here too.
  "BaseContract",
  ...BASE_CONTRACT_TYPE_IMPORT_NAMES,
];

function reservedBaseContractImportNames(includeLeoValueImport: boolean): readonly string[] {
  return [
    ...new Set([
      ...baseContractValueImportNames(includeLeoValueImport),
      ...RESERVED_BASE_CONTRACT_TYPE_IMPORT_NAMES,
    ]),
  ];
}

/**
 * Instance members (public + protected + private) of the `BaseContract` class
 * in contract-wrapper.ts. A transition whose generated `readonly ${name}`
 * accessor equals one of these redeclares an inherited member (TS2416/2425),
 * and several are also called by generated transition bodies via `this.${name}`.
 * The `mappings`/`storage` containers are reserved separately (only when the
 * program actually emits them). Kept in sync with the BaseContract class by the
 * "stays in sync with BaseContract instance members" test in
 * typescript-generator.test.ts, which derives the member set from the emitted
 * class source and asserts every member is rejected here.
 */
const RESERVED_CONTRACT_INSTANCE_MEMBERS: readonly string[] = [
  // the generated class always emits `constructor(options?)`, so a transition
  // named `constructor` would redeclare it
  "constructor",
  // properties
  "programId",
  "instanceImports",
  "lre",
  "signer",
  // public methods
  "connect",
  "address",
  "withSigner",
  // protected / private methods
  "inputContext",
  "getLre",
  "getNetwork",
  "executeLocal",
  "expectLocalFailure",
  "submitTransition",
  "settleTransition",
  "expectAccepted",
  "expectRejected",
  "settleTyped",
  "expectAcceptedTyped",
  "runProjector",
  "outputAt",
  "executeRaw",
  "buildEffectiveOptions",
  "queryMapping",
  "mappingContains",
  "requireMappingRaw",
  "queryStorage",
  "requireStorageRaw",
  "queryStorageVectorLength",
  "queryStorageVector",
  "requireStorageVectorRaw",
  "queryStorageVectorAll",
  "selectAcceptedTransition",
  "selectRejectedTransitionOutputs",
];

/**
 * A local struct/record whose generated interface name equals a fixed
 * BaseContract import (e.g. `LeoField`, `BaseContract`) collides with that
 * import (TS2440). Interface names mirror the Leo declaration and can't be
 * silently renamed like the contract class, so fail with a clear message.
 */
function assertNoReservedLocalTypeNames(abi: ProgramABI): void {
  const reserved = new Set<string>(RESERVED_BASE_CONTRACT_TYPE_IMPORT_NAMES);
  const check = (kind: "struct" | "record", path: readonly string[]): void => {
    const name = pathToTsName(path);
    if (reserved.has(name)) {
      throw new CodegenError(
        `Program ${abi.program} declares a ${kind} '${name}', whose generated interface collides with the reserved binding '${name}' imported from BaseContract. Rename the ${kind}.`,
        { programId: abi.program, typeName: name, kind, phase: "generate" },
      );
    }
  };
  for (const struct of abi.structs) check("struct", struct.path);
  for (const record of abi.records) check("record", record.path);
}

/**
 * A transition whose generated `readonly ${name}` accessor collides with an
 * inherited BaseContract member, or with the `mappings`/`storage` container when
 * the program has mappings/storage. These can't be auto-renamed without changing
 * the public call API (`contract.${name}`), so fail with a clear message.
 */
function assertNoReservedContractMembers(abi: ProgramABI): void {
  const reserved = new Set<string>(RESERVED_CONTRACT_INSTANCE_MEMBERS);
  if (abi.mappings.length > 0) reserved.add("mappings");
  if (abi.storage_variables.length > 0) reserved.add("storage");
  for (const transition of abi.transitions) {
    if (reserved.has(transition.name)) {
      throw new CodegenError(
        `Program ${abi.program} has a transition '${transition.name}' whose generated accessor collides with a reserved contract member (inherited BaseContract members such as connect/withSigner/address/programId, or the mappings/storage container). Rename the transition.`,
        { programId: abi.program, transition: transition.name, phase: "generate" },
      );
    }
  }
}

/**
 * A dynamic-record helper is emitted as a module-level `export const
 * ${helperName} = Object.assign(_${helperName}Impl, …)`, backed by a sibling
 * `function _${helperName}Impl(…)`. Reject a helper whose name equals any other
 * module-level value binding the generator emits, since two `const`s (or a
 * `const`/`function` and an imported value) of the same name is a duplicate
 * declaration (TS2451/TS2440):
 *   - the fixed BaseContract value imports (`BaseContract`,
 *     `createRecordOutputMatcher`, and `Leo` whenever helpers are emitted),
 *   - the contract class and its `create${class}` factory,
 *   - the per-type `serialize`/`deserialize`/`decrypt` consts,
 *   - the external ref serializer/deserializer aliases and record value bindings
 *     imported/re-exported for cross-program types (e.g. `serializeGoldToken_Token`),
 *   - the `_${otherHelper}Impl` backing function of any other helper (e.g. a
 *     helper `_asReceiptImpl` clashes with helper `asReceipt`'s impl function).
 * The contract class is silently suffixed away from such collisions, but a
 * helper name is user-chosen config (`codegen.dynamicRecords`) that can't be
 * renamed without changing the call API, so fail with a clear message instead.
 */
function assertNoReservedHelperNames(
  abi: ProgramABI,
  className: string,
  includeLeoValueImport: boolean,
  helpers: readonly { readonly helperName: string }[],
  externalInfos: Iterable<ExternalRefInfo>,
): void {
  if (helpers.length === 0) return;
  // Reserved value-binding name -> short description of what it would clash with.
  const reserved = new Map<string, string>();
  for (const name of baseContractValueImportNames(includeLeoValueImport)) {
    reserved.set(name, `the '${name}' value imported from BaseContract`);
  }
  reserved.set(className, `the contract class '${className}'`);
  reserved.set(`create${className}`, `the contract factory 'create${className}'`);
  for (const struct of abi.structs) {
    const name = pathToTsName(struct.path);
    reserved.set(`serialize${name}`, `the generated 'serialize${name}'`);
    reserved.set(`deserialize${name}`, `the generated 'deserialize${name}'`);
  }
  for (const record of abi.records) {
    const name = pathToTsName(record.path);
    reserved.set(`serialize${name}`, `the generated 'serialize${name}'`);
    reserved.set(`deserialize${name}`, `the generated 'deserialize${name}'`);
    reserved.set(`decrypt${name}`, `the generated 'decrypt${name}'`);
  }
  // External refs import `serialize${Base} as ${serializerName}` /
  // `deserialize${Base} as ${deserializerName}` and (for records) re-export
  // `export const ${typeName}`. The type aliases already bump away from helper
  // names, but the serializer/deserializer value aliases do not — reserve them.
  for (const info of externalInfos) {
    reserved.set(info.serializerName, `the imported external serializer '${info.serializerName}'`);
    reserved.set(
      info.deserializerName,
      `the imported external deserializer '${info.deserializerName}'`,
    );
    reserved.set(info.typeName, `the external type binding '${info.typeName}'`);
  }
  // Each helper also emits a `function _${helperName}Impl` backing declaration.
  // `_${helperName}Impl` is never equal to its own helper's name, so this only
  // catches one helper's name colliding with another helper's impl function.
  for (const helper of helpers) {
    reserved.set(
      `_${helper.helperName}Impl`,
      `the backing function of dynamic-record helper '${helper.helperName}'`,
    );
  }
  for (const helper of helpers) {
    const clashesWith = reserved.get(helper.helperName);
    if (clashesWith !== undefined) {
      throw new CodegenError(
        `Program ${abi.program} configures a dynamic-record helper '${helper.helperName}', whose generated 'export const ${helper.helperName}' collides with ${clashesWith}. Rename the helper (codegen.dynamicRecords).`,
        { programId: abi.program, helperName: helper.helperName, phase: "generate" },
      );
    }
  }
}

interface GenerationContext {
  readonly programId: string;
  readonly programsById: ReadonlyMap<string, ProgramABI>;
  readonly structsByKey: ReadonlyMap<string, StructABI>;
  readonly recordsByKey: ReadonlyMap<string, RecordABI>;
  readonly externalStructRefs: ReadonlyMap<string, StructRef>;
  readonly externalRecordRefs: ReadonlyMap<string, RecordRef>;
  /**
   * Resolved import aliases for external struct/record refs, keyed by
   * `externalRefKey`. This is the single source of truth for external type
   * aliases and their serializer/deserializer aliases, so emission does not
   * recompute `${ProgramClass}_${TypeName}` at each call site.
   */
  readonly externalInfoByKey: ReadonlyMap<string, ExternalRefInfo>;
  /**
   * Resolved `${Name}Input` identifier for every local struct/record (keyed by
   * `pathKey`) and external struct/record ref (keyed by `externalRefKey`). The
   * single source of truth for input-type names — interface/alias emitters,
   * input binding routers, serializer signatures, and cast sites all read from
   * here rather than recomputing `${name}Input` by concatenation.
   */
  readonly inputNameByKey: ReadonlyMap<string, string>;
  /**
   * Local name under which `WidenInput` is imported from `BaseContract` (used by
   * external input aliases). Normally `"WidenInput"`, but mangled deterministically
   * (`WidenInput_`, …) if a generated output type/class is named `WidenInput`, so
   * the import never conflicts with a local declaration (TS2440).
   */
  readonly widenInputAlias: string;
}

function createGenerationContext(
  abi: ProgramABI,
  allAbis: readonly ProgramABI[],
  reservedHelperNames: readonly string[] = [],
  includeLeoValueImport = false,
): GenerationContext {
  const programsById = new Map<string, ProgramABI>();
  for (const programAbi of allAbis) {
    programsById.set(programAbi.program, programAbi);
  }
  programsById.set(abi.program, abi);

  const externalStructRefs = new Map<string, StructRef>();
  const externalRecordRefs = new Map<string, RecordRef>();
  collectExternalRefs(abi, programsById, externalStructRefs, externalRecordRefs);

  const externalInfoByKey = resolveExternalInfos(
    abi,
    externalStructRefs,
    externalRecordRefs,
    reservedHelperNames,
    includeLeoValueImport,
  );
  const { inputNameByKey, widenInputAlias } = resolveInputNames(
    abi,
    externalStructRefs,
    externalRecordRefs,
    externalInfoByKey,
    reservedHelperNames,
    includeLeoValueImport,
  );

  return {
    programId: abi.program,
    programsById,
    structsByKey: new Map(abi.structs.map((struct) => [pathKey(struct.path), struct])),
    recordsByKey: new Map(abi.records.map((record) => [pathKey(record.path), record])),
    externalStructRefs,
    externalRecordRefs,
    externalInfoByKey,
    inputNameByKey,
    widenInputAlias,
  };
}

/**
 * Names this module emits as top-level declarations from the program's own ABI:
 * the contract class, its `${class}Storage` interface, and every local
 * struct/record interface. Shared by the external-alias and input-name
 * disambiguation passes so they reserve an identical base set. `${class}Storage`
 * is reserved even when the program has no storage variables — harmless
 * over-reservation that only ever yields more-unique names.
 */
function localDeclaredNames(abi: ProgramABI, includeLeoValueImport: boolean): string[] {
  const className = resolveContractClassName(abi, { includeLeoValueImport });
  return [
    className,
    `${className}Storage`,
    ...abi.structs.map((s) => pathToTsName(s.path)),
    ...abi.records.map((r) => pathToTsName(r.path)),
  ];
}

/**
 * Stable ordering for external refs by their `externalRefKey`, so underscore
 * disambiguation is deterministic across runs.
 */
function sortRefsByKey<T extends StructRef | RecordRef>(refs: Iterable<T>): T[] {
  return [...refs].sort((a, b) => externalRefKey(a).localeCompare(externalRefKey(b)));
}

/**
 * Build deterministic external type/helper aliases before emission so imports,
 * type annotations, serializers, and deserializers all use the same resolved
 * names. The preferred alias is `${ProgramClass}_${TypeName}`; underscores are
 * appended only when needed to avoid a local declaration in this module.
 */
function resolveExternalInfos(
  abi: ProgramABI,
  externalStructRefs: ReadonlyMap<string, StructRef>,
  externalRecordRefs: ReadonlyMap<string, RecordRef>,
  reservedHelperNames: readonly string[] = [],
  includeLeoValueImport = false,
): Map<string, ExternalRefInfo> {
  const reserved = new Set<string>([
    ...localDeclaredNames(abi, includeLeoValueImport),
    ...reservedHelperNames,
  ]);
  // Structs and records share one map keyed by `externalRefKey` (program+path).
  // Leo keeps structs and records in a single type namespace, so no struct and
  // record can share a program+path — entries never alias each other here.
  const infoByKey = new Map<string, ExternalRefInfo>();

  const claim = (ref: StructRef | RecordRef, baseName: string): void => {
    const programId = ref.program!;
    const programClass = programIdToClassName(programId);
    const preferred = `${programClass}_${baseName}`;
    let typeName = preferred;
    let underscores = 1;
    while (reserved.has(typeName)) {
      typeName = `${preferred}${"_".repeat(underscores)}`;
      underscores++;
    }
    reserved.add(typeName);
    infoByKey.set(externalRefKey(ref), {
      programId,
      className: programClass,
      baseName,
      typeName,
      serializerName: `serialize${typeName}`,
      deserializerName: `deserialize${typeName}`,
    });
  };

  for (const ref of sortRefsByKey(externalStructRefs.values())) claim(ref, structRefName(ref));
  for (const ref of sortRefsByKey(externalRecordRefs.values())) claim(ref, recordRefName(ref));

  return infoByKey;
}

/**
 * Identifiers imported from `BaseContract` that end in `Input` (the only fixed
 * imports a `${name}Input` alias could collide with).
 */
const RESERVED_INPUT_IMPORTS: readonly string[] = [
  "AddressInput",
  "FieldInput",
  "GroupInput",
  "ScalarInput",
  "IdentifierInput",
  "DynamicRecordInput",
  "PlaintextInput",
  "WidenInput",
];

/**
 * Build the deterministic `${Name}Input` map for all local and external
 * struct/record types. Runs before any emission; output is a pure function of
 * the ABI set + the fixed import list, so it is reproducible across runs.
 */
function resolveInputNames(
  abi: ProgramABI,
  externalStructRefs: ReadonlyMap<string, StructRef>,
  externalRecordRefs: ReadonlyMap<string, RecordRef>,
  externalInfoByKey: ReadonlyMap<string, ExternalRefInfo>,
  reservedHelperNames: readonly string[] = [],
  includeLeoValueImport = false,
): { inputNameByKey: Map<string, string>; widenInputAlias: string } {
  // `declared` = names this module emits as top-level declarations (interfaces,
  // class, storage, external re-exports, dynamic-record helper consts, and the
  // input aliases claimed below). Kept distinct from the fixed imports so the
  // WidenInput import alias can be checked against genuine declaration
  // collisions only.
  const declared = new Set<string>([
    ...localDeclaredNames(abi, includeLeoValueImport),
    ...reservedHelperNames,
  ]);
  for (const ref of externalStructRefs.values()) {
    declared.add(externalInfoByKey.get(externalRefKey(ref))!.typeName);
  }
  for (const ref of externalRecordRefs.values()) {
    declared.add(externalInfoByKey.get(externalRefKey(ref))!.typeName);
  }
  const reserved = new Set<string>([...RESERVED_INPUT_IMPORTS, ...declared]);

  const inputNameByKey = new Map<string, string>();
  const claim = (key: string, base: string): void => {
    const name = disambiguateInputName(base, reserved);
    reserved.add(name);
    declared.add(name);
    inputNameByKey.set(key, name);
  };

  // Deterministic order: local structs, then local records (ABI order), then
  // external structs and records sorted by their stable ref key.
  for (const struct of abi.structs) claim(pathKey(struct.path), pathToTsName(struct.path));
  for (const record of abi.records) claim(pathKey(record.path), pathToTsName(record.path));
  for (const ref of sortRefsByKey(externalStructRefs.values())) {
    claim(externalRefKey(ref), externalInfoByKey.get(externalRefKey(ref))!.typeName);
  }
  for (const ref of sortRefsByKey(externalRecordRefs.values())) {
    claim(externalRefKey(ref), externalInfoByKey.get(externalRefKey(ref))!.typeName);
  }

  // Choose a local name for the imported `WidenInput` that no generated
  // declaration shadows (a local type/class literally named `WidenInput` would
  // otherwise conflict with the import — TS2440). Checked against `declared`
  // only, not the fixed imports.
  const forbidden = declared;
  let widenInputAlias = "WidenInput";
  let underscores = 1;
  while (forbidden.has(widenInputAlias)) {
    widenInputAlias = `WidenInput${"_".repeat(underscores)}`;
    underscores++;
  }

  return { inputNameByKey, widenInputAlias };
}

/** Resolved input-type name for a struct ref (local or external). */
function structInputName(ref: StructRef, ctx: GenerationContext): string {
  const key = isLocalStructRef(ref, ctx) ? pathKey(ref.path) : externalRefKey(ref);
  return ctx.inputNameByKey.get(key) ?? `${structRefName(ref)}Input`;
}

/** Resolved input-type name for a record ref (local or external). */
function recordInputName(ref: RecordRef, ctx: GenerationContext): string {
  const key = isLocalRecordRef(ref, ctx) ? pathKey(ref.path) : externalRefKey(ref);
  return ctx.inputNameByKey.get(key) ?? `${recordRefName(ref)}Input`;
}

function collectExternalRefs(
  abi: ProgramABI,
  programsById: ReadonlyMap<string, ProgramABI>,
  structs: Map<string, StructRef>,
  records: Map<string, RecordRef>,
): void {
  const addStruct = (ref: StructRef): void => {
    if (!ref.program || ref.program === abi.program) return;
    const programAbi = programsById.get(ref.program);
    if (!programAbi?.structs.some((struct) => pathKey(struct.path) === pathKey(ref.path))) return;
    structs.set(externalRefKey(ref), ref);
  };

  const addRecord = (ref: RecordRef): void => {
    if (!ref.program || ref.program === abi.program) return;
    const programAbi = programsById.get(ref.program);
    if (!programAbi?.records.some((record) => pathKey(record.path) === pathKey(ref.path))) return;
    records.set(externalRefKey(ref), ref);
  };

  const visitPlaintext = (ty: PlaintextType): void => {
    if ("Struct" in ty) {
      addStruct(ty.Struct);
      return;
    }
    if ("Array" in ty) {
      visitPlaintext(ty.Array[0]);
      return;
    }
    if ("Optional" in ty) {
      visitPlaintext(ty.Optional);
    }
  };

  const visitAleo = (ty: AleoType): void => {
    if (ty === "DynamicRecord") return;
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext);
      return;
    }
    if ("Record" in ty) {
      addRecord(ty.Record);
    }
  };

  const visitStorage = (ty: StorageType): void => {
    if ("Plaintext" in ty) {
      visitPlaintext(ty.Plaintext);
      return;
    }
    if ("Vector" in ty) {
      visitStorage(ty.Vector);
    }
  };

  for (const struct of abi.structs) {
    for (const field of struct.fields) visitPlaintext(field.ty);
  }
  for (const record of abi.records) {
    for (const field of record.fields) visitPlaintext(field.ty);
  }
  for (const mapping of abi.mappings) {
    visitPlaintext(mapping.key);
    visitPlaintext(mapping.value);
  }
  for (const variable of abi.storage_variables) visitStorage(variable.ty);
  for (const transition of abi.transitions) {
    for (const input of transition.inputs) visitAleo(input.ty);
    for (const output of transition.outputs) visitAleo(output.ty);
  }
}

// ---------------------------------------------------------------------------
// Struct/Record/Storage interface generation
// ---------------------------------------------------------------------------

function generateStructInterface(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  for (const field of struct.fields) {
    lines.push(`  readonly ${field.name}: ${plaintextToOutputBindingTs(field.ty, ctx)};`);
  }
  lines.push("}");
  return lines;
}

function generateRecordInterface(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  lines.push("  readonly owner: LeoAddress;");
  for (const field of record.fields) {
    if (["owner", "_nonce"].includes(field.name)) continue;
    lines.push(`  readonly ${field.name}: ${plaintextToOutputBindingTs(field.ty, ctx)};`);
  }
  lines.push("  readonly _nonce: LeoGroup;");
  lines.push("}");
  return lines;
}

/**
 * Widened input interface mirroring `generateStructInterface` but typing every
 * field via the input binding (scalar fields accept `bigint | number`, nested
 * composites widen recursively). Used for transition args, mapping keys, and
 * serializer inputs; the branded interface above is kept for outputs/reads.
 */
function generateStructInputInterface(struct: StructABI, ctx: GenerationContext): string[] {
  const name = ctx.inputNameByKey.get(pathKey(struct.path)) ?? `${pathToTsName(struct.path)}Input`;
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  for (const field of struct.fields) {
    lines.push(`  readonly ${field.name}: ${plaintextToInputBindingTs(field.ty, ctx)};`);
  }
  lines.push("}");
  return lines;
}

/** Widened input interface for a record (`owner`/`_nonce` widened to their *Input aliases). */
function generateRecordInputInterface(record: RecordABI, ctx: GenerationContext): string[] {
  const name = ctx.inputNameByKey.get(pathKey(record.path)) ?? `${pathToTsName(record.path)}Input`;
  const lines: string[] = [];
  lines.push(`export interface ${name} {`);
  lines.push("  readonly owner: AddressInput;");
  for (const field of record.fields) {
    if (field.name === "owner") continue;
    lines.push(`  readonly ${field.name}: ${plaintextToInputBindingTs(field.ty, ctx)};`);
  }
  lines.push("  readonly _nonce: GroupInput;");
  lines.push("}");
  return lines;
}

function generateStorageInterface(
  className: string,
  storageVariables: readonly StorageVariableABI[],
  ctx: GenerationContext,
): string[] {
  const lines: string[] = [];
  lines.push(`export interface ${className}Storage {`);
  for (const variable of storageVariables) {
    lines.push(`  readonly ${variable.name}: ${storageTypeToBindingTs(variable.ty, ctx)};`);
  }
  lines.push("}");
  return lines;
}

// ---------------------------------------------------------------------------
// Serialization helpers
// ---------------------------------------------------------------------------

function generateStructSerializer(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const inputName = ctx.inputNameByKey.get(pathKey(struct.path)) ?? `${name}Input`;
  const lines: string[] = [];
  lines.push(
    `export function serialize${name}(value: ${inputName}, context?: TransitionInputContext): string {`,
  );
  lines.push("  BaseContract.assertObject(value, context);");
  lines.push("  const fields: string[] = [];");

  for (const field of struct.fields) {
    const serialized = serializePlaintextExpr(
      `value.${field.name}`,
      field.ty,
      ctx,
      `BaseContract.childInputContext(context, "${field.name}")`,
    );
    lines.push(`  fields.push("${field.name}: " + ${serialized});`);
  }

  lines.push('  return "{ " + fields.join(", ") + " }";');
  lines.push("}");
  return lines;
}

function generateRecordSerializer(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const inputName = ctx.inputNameByKey.get(pathKey(record.path)) ?? `${name}Input`;
  const lines: string[] = [];
  lines.push(
    `export function serialize${name}(value: ${inputName}, context?: TransitionInputContext): string {`,
  );
  lines.push("  BaseContract.assertObject(value, context);");
  // Round-trip a record returned by a previous transition by replaying the
  // original literal verbatim. Without this, per-field visibility suffixes
  // mismatch on re-serialization and the runtime rejects the input. See
  // BaseContract.RECORD_RAW.
  lines.push(
    "  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];",
  );
  lines.push('  if (typeof _raw === "string") return _raw;');
  lines.push("  const fields: string[] = [];");

  for (const field of record.fields) {
    const serialized = serializePlaintextExpr(
      `value.${field.name}`,
      field.ty,
      ctx,
      `BaseContract.childInputContext(context, "${field.name}")`,
    );
    lines.push(`  fields.push("${field.name}: " + ${serialized});`);
  }
  lines.push(
    '  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));',
  );

  lines.push('  return "{ " + fields.join(", ") + " }";');
  lines.push("}");
  return lines;
}

function generateStructDeserializer(struct: StructABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(struct.path);
  const lines: string[] = [];
  lines.push(`export function deserialize${name}(value: string): ${name} {`);
  lines.push("  const _fields = BaseContract.parseStruct(value);");
  lines.push("  return {");
  for (const field of struct.fields) {
    lines.push(
      `    ${field.name}: ${deserializePlaintextExpr(`_fields["${field.name}"]!`, field.ty, ctx)},`,
    );
  }
  lines.push("  };");
  lines.push("}");
  return lines;
}

function generateRecordDecryptor(record: RecordABI): string[] {
  const name = pathToTsName(record.path);
  return [
    `export async function decrypt${name}(ciphertext: string, key: RecordDecryptionKey): Promise<${name}> {`,
    `  return BaseContract.decryptRecord(ciphertext, key, deserialize${name});`,
    "}",
  ];
}

/**
 * Emit a free function that converts a generated record value into a typed
 * `LeoDynamicRecord` literal using `Leo.dynamicRecord(value, schema)`. The
 * schema is fixed at codegen time from `helper.schema`; the generated
 * function takes only the record value.
 *
 * Validates the helper config against the source record's generated shape:
 * - implicit `owner: address` field
 * - each ABI record field (excluding any explicit `owner` re-declaration)
 * - implicit `_nonce: group` field
 *
 * Mismatches and unsupported primitive types throw `CodegenError` so users
 * get a precise build-time failure instead of a runtime parser error.
 */
function generateDynamicRecordHelper(
  helper: ResolvedDynamicRecordHelperEmit,
  abi: ProgramABI,
  ctx: GenerationContext,
): string[] {
  const record = abi.records.find((r) => pathToTsName(r.path) === helper.sourceRecord);
  if (!record) {
    throw new CodegenError(
      `codegen.dynamicRecords.${helper.helperName}: sourceRecord '${helper.sourceRecord}' is not a local record in '${abi.program}'.`,
      { helperName: helper.helperName, sourceRecord: helper.sourceRecord, program: abi.program },
    );
  }

  const expectedFields = buildExpectedFieldsForHelper(helper, record);

  const schemaKeys = Object.keys(helper.schema);
  const missing = [...expectedFields.keys()].filter((k) => !Object.hasOwn(helper.schema, k));
  const extra = schemaKeys.filter((k) => !expectedFields.has(k));
  if (missing.length > 0 || extra.length > 0) {
    throw new CodegenError(
      `codegen.dynamicRecords.${helper.helperName}: schema keys do not match record '${helper.sourceRecord}'. Missing: [${missing.join(", ")}]; Extra: [${extra.join(", ")}].`,
      {
        helperName: helper.helperName,
        sourceRecord: helper.sourceRecord,
        missing,
        extra,
      },
    );
  }

  for (const fieldName of schemaKeys) {
    const entry = helper.schema[fieldName]!;
    const dot = entry.lastIndexOf(".");
    if (dot < 0) {
      throw new CodegenError(
        `codegen.dynamicRecords.${helper.helperName}.schema.${fieldName}: '${entry}' is not a valid '<type>.<visibility>' schema entry.`,
        { helperName: helper.helperName, field: fieldName, schemaEntry: entry },
      );
    }
    const schemaPrim = entry.slice(0, dot);
    const expectedPrim = expectedFields.get(fieldName)!;
    if (schemaPrim !== expectedPrim) {
      throw new CodegenError(
        `codegen.dynamicRecords.${helper.helperName}.schema.${fieldName}: field has Leo type '${expectedPrim}' on record '${helper.sourceRecord}', but schema says '${schemaPrim}'.`,
        {
          helperName: helper.helperName,
          field: fieldName,
          expected: expectedPrim,
          actual: schemaPrim,
        },
      );
    }
  }

  const lines: string[] = [];
  const fnName = `_${helper.helperName}Impl`;
  // `value` is widened to the record's resolved input interface so callers may
  // pass raw field values; `.output` (below) stays the branded record type.
  const inputName = ctx.inputNameByKey.get(pathKey(record.path)) ?? `${helper.sourceRecord}Input`;
  lines.push(`function ${fnName}(value: ${inputName}): LeoDynamicRecord {`);
  lines.push("  return Leo.dynamicRecord(value, {");
  for (const [key, entry] of Object.entries(helper.schema)) {
    lines.push(`    ${key}: ${JSON.stringify(entry)} as const,`);
  }
  lines.push("  } as const);");
  lines.push("}");
  // Callable + namespace pattern: the helper is also a namespace carrying
  // `output`, the output-side matcher. Used by callers refining record
  // decryption via an id-only handle's `.match(matcher.from(...)|.at(...))`
  // or the encrypted-record arm's `.match(matcher)`.
  lines.push(`export const ${helper.helperName} = Object.assign(${fnName}, {`);
  lines.push(`  output: createRecordOutputMatcher<${helper.sourceRecord}>({`);
  lines.push(`    program: "${abi.program}",`);
  lines.push(`    recordName: "${helper.sourceRecord}",`);
  lines.push(`    deserialize: deserialize${helper.sourceRecord},`);
  lines.push(`  }),`);
  lines.push("});");
  return lines;
}

/**
 * Build the expected `<fieldName, primitive>` map matching the generated
 * record interface shape:
 *   1. implicit `owner: address`
 *   2. each ABI field that isn't a re-declaration of `owner`
 *   3. implicit `_nonce: group`
 *
 * Rejects unsupported ABI primitives (Identifier, Signature) and non-primitive
 * fields (struct, array, optional). These cases cannot be encoded by
 * `Leo.dynamicRecord` even though they may appear in a record's serialized form.
 */
function buildExpectedFieldsForHelper(
  helper: ResolvedDynamicRecordHelperEmit,
  record: RecordABI,
): Map<string, string> {
  const expectedFields = new Map<string, string>();
  expectedFields.set("owner", "address");
  for (const field of record.fields) {
    if (field.name === "owner") continue;
    const prim = primitiveOfPlaintext(field.ty);
    if (prim === null) {
      throw new CodegenError(
        `codegen.dynamicRecords.${helper.helperName}: record '${helper.sourceRecord}' contains non-primitive field '${field.name}'. Interface conversion helpers only support primitive record fields.`,
        { helperName: helper.helperName, sourceRecord: helper.sourceRecord, field: field.name },
      );
    }
    if (!SUPPORTED_DYNAMIC_RECORD_PRIMITIVES.has(prim)) {
      throw new CodegenError(
        `codegen.dynamicRecords.${helper.helperName}: record '${helper.sourceRecord}' field '${field.name}' uses unsupported primitive '${prim}'. Leo.dynamicRecord only supports: ${[...SUPPORTED_DYNAMIC_RECORD_PRIMITIVES].join("/")}.`,
        {
          helperName: helper.helperName,
          sourceRecord: helper.sourceRecord,
          field: field.name,
          primitive: prim,
        },
      );
    }
    expectedFields.set(field.name, prim);
  }
  expectedFields.set("_nonce", "group");
  return expectedFields;
}

/**
 * Map a PlaintextType primitive to its Leo source-level name (lowercase),
 * matching the keys of `serializeDynamicRecordField`'s dispatch table.
 * Returns null for non-primitive types (struct, array, optional).
 */
function primitiveOfPlaintext(ty: PlaintextType): string | null {
  if (typeof ty !== "object" || ty === null) return null;
  if (!("Primitive" in ty)) return null;
  const prim = ty.Primitive;
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return "address";
      case "Boolean":
        return "boolean";
      case "Field":
        return "field";
      case "Group":
        return "group";
      case "Scalar":
        return "scalar";
      case "Identifier":
        return "identifier";
    }
    return null;
  }
  if (typeof prim === "object" && prim !== null) {
    if ("UInt" in prim) return prim.UInt.toLowerCase();
    if ("Int" in prim) return prim.Int.toLowerCase();
  }
  return null;
}

function generateRecordDeserializer(record: RecordABI, ctx: GenerationContext): string[] {
  const name = pathToTsName(record.path);
  const lines: string[] = [];
  lines.push(`export function deserialize${name}(value: string): ${name} {`);
  lines.push("  const _fields = BaseContract.parseStruct(value);");
  lines.push(`  const _record: ${name} = {`);
  lines.push('    owner: BaseContract.parseAddress(_fields["owner"]!),');
  for (const field of record.fields) {
    if (field.name === "owner") continue;
    lines.push(
      `    ${field.name}: ${deserializePlaintextExpr(`_fields["${field.name}"]!`, field.ty, ctx)},`,
    );
  }
  lines.push('    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),');
  lines.push("  };");
  // Stash the original literal so serialize${name} can replay it verbatim
  // and avoid mangling per-field visibility suffixes on round-trip.
  lines.push(
    "  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });",
  );
  lines.push("  return _record;");
  lines.push("}");
  return lines;
}

// ---------------------------------------------------------------------------
// Contract class generation
// ---------------------------------------------------------------------------

function generateContractClass(
  abi: ProgramABI,
  className: string,
  ctx: GenerationContext,
): string[] {
  const lines: string[] = [];

  lines.push(`export class ${className} extends BaseContract {`);
  lines.push("  constructor(options?: BaseContractOptions) {");
  lines.push(`    super("${abi.program}", options);`);
  lines.push("  }");

  for (const transition of abi.transitions) {
    lines.push("");
    lines.push(...indentLines(generateTransitionMethod(transition, ctx), "  "));
  }

  if (abi.mappings.length > 0) {
    const propKeys = buildMappingPropKeys(abi.mappings);
    lines.push("");
    lines.push("  readonly mappings = {");
    for (const mapping of abi.mappings) {
      lines.push(...indentLines(generateMappingAccessor(mapping, propKeys, ctx), "    "));
    }
    lines.push("  } as const;");
  }

  if (abi.storage_variables.length > 0) {
    const propKeys = buildStoragePropKeys(abi.storage_variables);
    lines.push("");
    lines.push("  readonly storage = {");
    for (const variable of abi.storage_variables) {
      lines.push(...indentLines(generateStorageAccessor(variable, propKeys, ctx), "    "));
    }
    lines.push("  } as const;");
  }

  lines.push("}");
  lines.push("");
  lines.push(`export function create${className}(options?: BaseContractOptions): ${className} {`);
  lines.push(`  return new ${className}(options);`);
  lines.push("}");

  return lines;
}

function generateTransitionMethod(transition: TransitionABI, ctx: GenerationContext): string[] {
  const lines: string[] = [];
  const hasInputs = transition.inputs.length > 0;
  const argsType = formatArgsObjectType(transition.inputs, ctx);
  const returnType = formatReturnType(transition.outputs, ctx);

  lines.push(`readonly ${transition.name} = {`);
  lines.push(
    `  locally: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<${returnType}> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(
    `    const _result = await this.executeLocal("${transition.name}", _args, options ?? {});`,
  );

  if (transition.outputs.length === 1) {
    const output = transition.outputs[0]!;
    lines.push(
      `    return ${deserializeOutputExpr(`this.outputAt(_result, "${transition.name}", 0)`, output.ty, ctx)};`,
    );
  } else if (transition.outputs.length > 1) {
    const tupleType = formatReturnType(transition.outputs, ctx);
    const elems = transition.outputs.map((o, i) =>
      deserializeOutputExpr(`this.outputAt(_result, "${transition.name}", ${i})`, o.ty, ctx),
    );
    lines.push(`    const _decoded: ${tupleType} = [${elems.join(", ")}];`);
    lines.push("    return _decoded;");
  } else {
    lines.push("    return undefined as any;");
  }

  lines.push("  },");
  lines.push("");
  lines.push(
    `  failsLocally: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<void> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    await this.expectLocalFailure("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(
    `  captureLocalFailure: async (${formatTransitionMethodParams(hasInputs, argsType, "LocalExecutionOptions")}): Promise<LocalTransitionError> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.expectLocalFailure("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  const typedOutputType = formatTypedOutputType(transition.outputs, ctx);
  const projectorExpr = formatProjectorExpr(transition, ctx.programId, ctx);

  lines.push(
    `  submitted: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<SubmittedTransition> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.submitTransition("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("");
  lines.push(
    `  settled: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<AcceptedTransition<${typedOutputType}> | RejectedTransition> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(
    `    return this.settleTyped("${transition.name}", _args, options ?? {}, ${projectorExpr});`,
  );
  lines.push("  },");
  lines.push("");
  lines.push(
    `  accepted: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<AcceptedTransition<${typedOutputType}>> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(
    `    return this.expectAcceptedTyped("${transition.name}", _args, options ?? {}, ${projectorExpr});`,
  );
  lines.push("  },");
  lines.push("");
  lines.push(
    `  rejected: async (${formatTransitionMethodParams(hasInputs, argsType, "OnChainExecutionOptions")}): Promise<RejectedTransition> => {`,
  );
  lines.push(...generateSerializedArgsLines(transition, ctx, "    "));
  lines.push(`    return this.expectRejected("${transition.name}", _args, options ?? {});`);
  lines.push("  },");
  lines.push("} as const;");

  return lines;
}

function generateSerializedArgsLines(
  transition: TransitionABI,
  ctx: GenerationContext,
  indent: string,
): string[] {
  const lines = [`${indent}const _args: string[] = [`];
  for (const input of transition.inputs) {
    lines.push(`${indent}  ${serializeInputExpr(input, transition.name, ctx)},`);
  }
  lines.push(`${indent}];`);
  return lines;
}

function generateMappingAccessor(
  mapping: MappingABI,
  propKeys: Map<string, string>,
  ctx: GenerationContext,
): string[] {
  const propKey = propKeys.get(mapping.name) ?? JSON.stringify(mapping.name);
  const keyType = plaintextToInputBindingTs(mapping.key, ctx);
  const valueType = plaintextToOutputBindingTs(mapping.value, ctx);
  const keySerializer = serializePlaintextExpr(
    "key",
    mapping.key,
    ctx,
    `{ programId: this.programId, input: "${mapping.name} key" }`,
  );
  const valueDeserializer = deserializePlaintextExpr("_result", mapping.value, ctx);

  return [
    `${propKey}: {`,
    `  contains: async (key: ${keyType}): Promise<boolean> => {`,
    `    return this.mappingContains("${mapping.name}", ${keySerializer});`,
    `  },`,
    `  get: async (key: ${keyType}): Promise<${valueType}> => {`,
    `    const _result = await this.requireMappingRaw("${mapping.name}", ${keySerializer});`,
    `    return ${valueDeserializer};`,
    `  },`,
    `  getOrUse: async (key: ${keyType}, def: ${valueType}): Promise<${valueType}> => {`,
    `    const _result = await this.queryMapping("${mapping.name}", ${keySerializer});`,
    `    if (_result === null) return def;`,
    `    return ${valueDeserializer};`,
    `  },`,
    `  tryGet: async (key: ${keyType}): Promise<${valueType} | null> => {`,
    `    const _result = await this.queryMapping("${mapping.name}", ${keySerializer});`,
    `    if (_result === null) return null;`,
    `    return ${valueDeserializer};`,
    `  },`,
    `},`,
  ];
}

function generateStorageAccessor(
  variable: StorageVariableABI,
  propKeys: Map<string, string>,
  ctx: GenerationContext,
): string[] {
  const propKey = propKeys.get(variable.name) ?? JSON.stringify(variable.name);
  if ("Vector" in variable.ty) {
    const valueType = storageTypeToBindingTs(variable.ty.Vector, ctx);
    const valueDeserializer = deserializeStorageExpr("_result", variable.ty.Vector, ctx);
    const elementDeserializer = deserializeStorageExpr("e", variable.ty.Vector, ctx);

    return [
      `${propKey}: {`,
      `  len: async (): Promise<number> => {`,
      `    return this.queryStorageVectorLength("${variable.name}");`,
      `  },`,
      `  get: async (index: number): Promise<${valueType}> => {`,
      `    const _result = await this.requireStorageVectorRaw("${variable.name}", index);`,
      `    return ${valueDeserializer};`,
      `  },`,
      `  getOrUse: async (index: number, def: ${valueType}): Promise<${valueType}> => {`,
      `    const _result = await this.queryStorageVector("${variable.name}", index);`,
      `    if (_result === null) return def;`,
      `    return ${valueDeserializer};`,
      `  },`,
      `  tryGet: async (index: number): Promise<${valueType} | null> => {`,
      `    const _result = await this.queryStorageVector("${variable.name}", index);`,
      `    if (_result === null) return null;`,
      `    return ${valueDeserializer};`,
      `  },`,
      `  getAll: async (): Promise<${valueType}[]> => {`,
      `    const _results = await this.queryStorageVectorAll("${variable.name}");`,
      `    return _results.map((e: string) => ${elementDeserializer});`,
      `  },`,
      `  toArray: async (): Promise<${valueType}[]> => {`,
      `    const _results = await this.queryStorageVectorAll("${variable.name}");`,
      `    return _results.map((e: string) => ${elementDeserializer});`,
      `  },`,
      `},`,
    ];
  }

  const valueType = storageTypeToBindingTs(variable.ty, ctx);
  const valueDeserializer = deserializeStorageExpr("_result", variable.ty, ctx);

  return [
    `${propKey}: {`,
    `  get: async (): Promise<${valueType}> => {`,
    `    const _result = await this.requireStorageRaw("${variable.name}");`,
    `    return ${valueDeserializer};`,
    `  },`,
    `  getOrUse: async (def: ${valueType}): Promise<${valueType}> => {`,
    `    const _result = await this.queryStorage("${variable.name}");`,
    `    if (_result === null) return def;`,
    `    return ${valueDeserializer};`,
    `  },`,
    `  tryGet: async (): Promise<${valueType} | null> => {`,
    `    const _result = await this.queryStorage("${variable.name}");`,
    `    if (_result === null) return null;`,
    `    return ${valueDeserializer};`,
    `  },`,
    `},`,
  ];
}

// ---------------------------------------------------------------------------
// Type mapping helpers used by code generation
// ---------------------------------------------------------------------------

function plaintextToOutputBindingTs(pt: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in pt) return primitiveOutputBindingTs(pt.Primitive);
  if ("Struct" in pt) {
    if (isLocalStructRef(pt.Struct, ctx)) return structRefName(pt.Struct);
    const external = externalStructInfo(pt.Struct, ctx);
    return external?.typeName ?? "LeoPlaintext";
  }
  if ("Array" in pt) {
    const [elemType] = pt.Array;
    return `ReadonlyArray<${plaintextToOutputBindingTs(elemType, ctx)}>`;
  }
  if ("Optional" in pt) return `${plaintextToOutputBindingTs(pt.Optional, ctx)} | null`;
  return "unknown";
}

function plaintextToInputBindingTs(pt: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in pt) return primitiveInputBindingTs(pt.Primitive);
  if ("Struct" in pt) {
    if (isLocalStructRef(pt.Struct, ctx)) return structInputName(pt.Struct, ctx);
    const external = externalStructInfo(pt.Struct, ctx);
    return external ? structInputName(pt.Struct, ctx) : "PlaintextInput";
  }
  if ("Array" in pt) {
    const [elemType] = pt.Array;
    return `ReadonlyArray<${plaintextToInputBindingTs(elemType, ctx)}>`;
  }
  if ("Optional" in pt) return `${plaintextToInputBindingTs(pt.Optional, ctx)} | null`;
  return "unknown";
}

function aleoTypeToOutputBindingTs(ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return "LeoDynamicRecord";
  if ("Plaintext" in ty) return plaintextToOutputBindingTs(ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return recordRefName(ty.Record);
    const external = externalRecordInfo(ty.Record, ctx);
    return external?.typeName ?? "LeoDynamicRecord";
  }
  if ("Future" in ty) return "void";
  return "unknown";
}

function aleoTypeToInputBindingTs(ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return "DynamicRecordInput";
  if ("Plaintext" in ty) return plaintextToInputBindingTs(ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return recordInputName(ty.Record, ctx);
    const external = externalRecordInfo(ty.Record, ctx);
    return external ? recordInputName(ty.Record, ctx) : "DynamicRecordInput";
  }
  if ("Future" in ty) return "void";
  return "unknown";
}

function storageTypeToBindingTs(ty: StorageType, ctx: GenerationContext): string {
  if ("Plaintext" in ty) return plaintextToOutputBindingTs(ty.Plaintext, ctx);
  if ("Vector" in ty) return `${storageTypeToBindingTs(ty.Vector, ctx)}[]`;
  return "unknown";
}

function primitiveOutputBindingTs(prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return "LeoAddress";
      case "Boolean":
        return "boolean";
      case "Field":
        return "LeoField";
      case "Group":
        return "LeoGroup";
      case "Identifier":
        return "LeoIdentifier";
      case "Scalar":
        return "LeoScalar";
    }
  }
  if (isBigIntType(prim)) return "bigint";
  return "number";
}

function primitiveInputBindingTs(prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return "AddressInput";
      case "Boolean":
        return "boolean";
      case "Field":
        return "FieldInput";
      case "Group":
        return "GroupInput";
      case "Identifier":
        return "IdentifierInput";
      case "Scalar":
        return "ScalarInput";
    }
  }
  if (isBigIntType(prim)) return "bigint";
  return "number";
}

// ---------------------------------------------------------------------------
// Serialization expression generators (JS value → Leo string)
// ---------------------------------------------------------------------------

function serializeInputExpr(
  input: AbiInput,
  transitionName: string,
  ctx: GenerationContext,
): string {
  return serializeAleoTypeExpr(
    `args.${input.name}`,
    input.ty,
    ctx,
    `this.inputContext("${transitionName}", "${input.name}")`,
  );
}

function serializeAleoTypeExpr(
  expr: string,
  ty: AleoType,
  ctx: GenerationContext,
  contextExpr = "undefined",
): string {
  if (ty === "DynamicRecord") return `BaseContract.serializeDynamicRecord(${expr}, ${contextExpr})`;
  if ("Plaintext" in ty) return serializePlaintextExpr(expr, ty.Plaintext, ctx, contextExpr);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) {
      const typeName = recordRefName(ty.Record);
      return `serialize${typeName}(${expr} as ${recordInputName(ty.Record, ctx)}, ${contextExpr})`;
    }
    const external = externalRecordInfo(ty.Record, ctx);
    return external
      ? `${external.serializerName}(${expr} as ${recordInputName(ty.Record, ctx)}, ${contextExpr})`
      : `BaseContract.serializeDynamicRecord(${expr}, ${contextExpr})`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

function serializePlaintextExpr(
  expr: string,
  ty: PlaintextType,
  ctx: GenerationContext,
  contextExpr = "undefined",
): string {
  if ("Primitive" in ty) return serializePrimitive(expr, ty.Primitive, contextExpr);
  if ("Struct" in ty) {
    if (isLocalStructRef(ty.Struct, ctx)) {
      const typeName = structRefName(ty.Struct);
      return `serialize${typeName}(${expr} as ${structInputName(ty.Struct, ctx)}, ${contextExpr})`;
    }
    const external = externalStructInfo(ty.Struct, ctx);
    return external
      ? `${external.serializerName}(${expr} as ${structInputName(ty.Struct, ctx)}, ${contextExpr})`
      : `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
  }
  if ("Array" in ty) {
    const [elemType] = ty.Array;
    const elemSer = serializePlaintextExpr("e", elemType, ctx, "context");
    return `BaseContract.serializeArray(${expr}, ${contextExpr}, (e: unknown, context: TransitionInputContext | undefined) => ${elemSer})`;
  }
  if ("Optional" in ty) {
    const innerSer = serializePlaintextExpr(expr, ty.Optional, ctx, contextExpr);
    const zero = zeroLeoValue(ty.Optional, ctx);
    if (zero !== null) {
      return `(${expr} != null ? "{ is_some: true, val: " + ${innerSer} + " }" : "{ is_some: false, val: ${zero} }")`;
    }
    return `(${expr} != null ? "{ is_some: true, val: " + ${innerSer} + " }" : BaseContract.serializeUnsupportedOptionalNone(${contextExpr}))`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

// ---------------------------------------------------------------------------
// Deserialization expression generators (Leo string → JS value)
// ---------------------------------------------------------------------------

function deserializeOutputExpr(expr: string, ty: AleoType, ctx: GenerationContext): string {
  if (ty === "DynamicRecord") return `BaseContract.parseDynamicRecord(${expr})`;
  if ("Plaintext" in ty) return deserializePlaintextExpr(expr, ty.Plaintext, ctx);
  if ("Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) return `deserialize${recordRefName(ty.Record)}(${expr})`;
    const external = externalRecordInfo(ty.Record, ctx);
    return external
      ? `${external.deserializerName}(${expr})`
      : `BaseContract.parseDynamicRecord(${expr})`;
  }
  if ("Future" in ty) return "undefined as any";
  return expr;
}

/**
 * Emit a `(plaintext: string) => T` function reference (or arrow) suitable
 * for passing as a deserializer callback — e.g. to
 * `BaseContract.makeEncryptedValue`. For primitive types we pass the
 * `BaseContract.parseXxx` method directly; for compound types we wrap in
 * an arrow so the deserialize logic stays at the callsite.
 */
function plaintextDeserializerFn(ty: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in ty) {
    const prim = ty.Primitive;
    if (typeof prim === "string") {
      switch (prim) {
        case "Address":
          return "BaseContract.parseAddress";
        case "Field":
          return "BaseContract.parseField";
        case "Group":
          return "BaseContract.parseGroup";
        case "Scalar":
          return "BaseContract.parseScalar";
        case "Identifier":
          return "BaseContract.parseIdentifier";
        case "Boolean":
          return "BaseContract.parseBoolean";
      }
    }
    if (typeof prim === "object" && prim !== null && ("UInt" in prim || "Int" in prim)) {
      return isBigIntType(prim) ? "BaseContract.parseBigInt" : "BaseContract.parseNumber";
    }
  }
  return `(_p: string) => ${deserializePlaintextExpr("_p", ty, ctx)}`;
}

function deserializePlaintextExpr(expr: string, ty: PlaintextType, ctx: GenerationContext): string {
  if ("Primitive" in ty) return deserializePrimitiveExpr(expr, ty.Primitive);
  if ("Struct" in ty) {
    if (isLocalStructRef(ty.Struct, ctx)) return `deserialize${structRefName(ty.Struct)}(${expr})`;
    const external = externalStructInfo(ty.Struct, ctx);
    return external
      ? `${external.deserializerName}(${expr})`
      : `BaseContract.parsePlaintext(${expr})`;
  }
  if ("Array" in ty) {
    const [elemType] = ty.Array;
    return `BaseContract.parseArray(${expr}).map((e: string) => ${deserializePlaintextExpr("e", elemType, ctx)})`;
  }
  if ("Optional" in ty) {
    return `(() => { const _opt = BaseContract.parseStruct(${expr}); return BaseContract.parseBoolean(_opt["is_some"]!) ? ${deserializePlaintextExpr('_opt["val"]!', ty.Optional, ctx)} : null; })()`;
  }
  return expr;
}

function deserializeStorageExpr(expr: string, ty: StorageType, ctx: GenerationContext): string {
  if ("Plaintext" in ty) return deserializePlaintextExpr(expr, ty.Plaintext, ctx);
  if ("Vector" in ty) {
    return `BaseContract.parseArray(${expr}).map((e: string) => ${deserializeStorageExpr("e", ty.Vector, ctx)})`;
  }
  return expr;
}

function deserializePrimitiveExpr(expr: string, prim: PrimitiveType): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return `BaseContract.parseAddress(${expr})`;
      case "Field":
        return `BaseContract.parseField(${expr})`;
      case "Group":
        return `BaseContract.parseGroup(${expr})`;
      case "Scalar":
        return `BaseContract.parseScalar(${expr})`;
      case "Identifier":
        return `BaseContract.parseIdentifier(${expr})`;
      case "Boolean":
        return `BaseContract.parseBoolean(${expr})`;
    }
    return expr;
  }
  if (typeof prim === "object" && prim !== null && ("UInt" in prim || "Int" in prim)) {
    if (isBigIntType(prim)) {
      return `BaseContract.parseBigInt(${expr})`;
    }
    return `BaseContract.parseNumber(${expr})`;
  }
  return expr;
}

function serializePrimitive(expr: string, prim: PrimitiveType, contextExpr = "undefined"): string {
  if (typeof prim === "string") {
    switch (prim) {
      case "Address":
        return `BaseContract.serializeAddress(${expr}, ${contextExpr})`;
      case "Field":
        return `BaseContract.serializeField(${expr}, ${contextExpr})`;
      case "Group":
        return `BaseContract.serializeGroup(${expr}, ${contextExpr})`;
      case "Scalar":
        return `BaseContract.serializeScalar(${expr}, ${contextExpr})`;
      case "Identifier":
        return `BaseContract.serializeIdentifier(${expr}, ${contextExpr})`;
      case "Boolean":
        return `BaseContract.serializeBoolean(${expr}, ${contextExpr})`;
    }
    return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
  }

  if (typeof prim === "object" && prim !== null && "UInt" in prim) {
    const bits = Number(prim.UInt.slice(1));
    return `BaseContract.serializeUInt(${expr}, ${bits}, ${contextExpr})`;
  }
  if (typeof prim === "object" && prim !== null && "Int" in prim) {
    const bits = Number(prim.Int.slice(1));
    return `BaseContract.serializeInt(${expr}, ${bits}, ${contextExpr})`;
  }
  return `BaseContract.serializePlaintext(${expr}, ${contextExpr})`;
}

// ---------------------------------------------------------------------------
// Zero-value helpers (for Optional None serialization)
// ---------------------------------------------------------------------------

function zeroLeoValue(
  ty: PlaintextType,
  ctx: GenerationContext,
  seen: ReadonlySet<string> = new Set(),
): string | null {
  if ("Primitive" in ty) {
    const prim = ty.Primitive;
    if (typeof prim === "string") {
      switch (prim) {
        case "Address":
          return "aleo1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3ljyzc";
        case "Boolean":
          return "false";
        case "Field":
          return "0field";
        case "Group":
          return "0group";
        case "Identifier":
          // Leo has no canonical zero identifier; Optional::None ignores val.
          return "'lionden_zero'";
        case "Scalar":
          return "0scalar";
      }
      return null;
    }
    if (typeof prim === "object" && prim !== null && "UInt" in prim)
      return `0${prim.UInt.toLowerCase()}`;
    if (typeof prim === "object" && prim !== null && "Int" in prim)
      return `0${prim.Int.toLowerCase()}`;
  }

  if ("Array" in ty) {
    const [elemType, length] = ty.Array;
    const elemZero = zeroLeoValue(elemType, ctx, seen);
    if (elemZero === null) return null;
    return `[${Array.from({ length }, () => elemZero).join(", ")}]`;
  }

  if ("Optional" in ty) {
    const innerZero = zeroLeoValue(ty.Optional, ctx, seen);
    if (innerZero === null) return null;
    return `{ is_some: false, val: ${innerZero} }`;
  }

  if ("Struct" in ty) {
    if (!isLocalStructRef(ty.Struct, ctx)) return null;

    const key = pathKey(ty.Struct.path);
    if (seen.has(key)) return null;

    const struct = ctx.structsByKey.get(key);
    if (!struct) return null;

    const nextSeen = new Set(seen);
    nextSeen.add(key);

    const fieldValues: string[] = [];
    for (const field of struct.fields) {
      const fieldZero = zeroLeoValue(field.ty, ctx, nextSeen);
      if (fieldZero === null) return null;
      fieldValues.push(`${field.name}: ${fieldZero}`);
    }
    return `{ ${fieldValues.join(", ")} }`;
  }

  return null;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface ExternalRefInfo {
  readonly programId: string;
  readonly className: string;
  readonly baseName: string;
  readonly typeName: string;
  readonly serializerName: string;
  readonly deserializerName: string;
}

function generateExternalImports(ctx: GenerationContext): string[] {
  const importsByProgram = new Map<string, Set<string>>();

  for (const ref of ctx.externalStructRefs.values()) {
    const info = externalStructInfo(ref, ctx);
    if (!info) continue;
    const imports = importsByProgram.get(info.programId) ?? new Set<string>();
    imports.add(`type ${info.baseName} as ${info.typeName}`);
    imports.add(`serialize${info.baseName} as ${info.serializerName}`);
    imports.add(`deserialize${info.baseName} as ${info.deserializerName}`);
    importsByProgram.set(info.programId, imports);
  }

  // External record types: alias the imported type under a private `_`-prefixed
  // name so we can re-export the public name as both a type alias and a value
  // binding (carrying `.output`).
  const externalRecords: ExternalRefInfo[] = [];
  for (const ref of ctx.externalRecordRefs.values()) {
    const info = externalRecordInfo(ref, ctx);
    if (!info) continue;
    externalRecords.push(info);
    const imports = importsByProgram.get(info.programId) ?? new Set<string>();
    imports.add(`type ${info.baseName} as _${info.typeName}`);
    imports.add(`serialize${info.baseName} as ${info.serializerName}`);
    imports.add(`deserialize${info.baseName} as ${info.deserializerName}`);
    importsByProgram.set(info.programId, imports);
  }

  const importLines = [...importsByProgram.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([programId, imports]) =>
        `import { ${[...imports].sort().join(", ")} } from "./${programIdToClassName(programId)}.js";`,
    );

  // Re-export each external record's type alias publicly, and emit a same-named
  // value binding carrying the `.output` matcher. The merged type + value
  // pair lets callers write both `IdOnlyExternalRecordHandle<GoldToken_Token>`
  // (type position) and `GoldToken_Token.output` (value position).
  const valueLines: string[] = [];
  for (const info of externalRecords.sort((a, b) => a.typeName.localeCompare(b.typeName))) {
    valueLines.push(`export type ${info.typeName} = _${info.typeName};`);
    valueLines.push(`export const ${info.typeName} = {`);
    valueLines.push(`  output: createRecordOutputMatcher<_${info.typeName}>({`);
    valueLines.push(`    program: "${info.programId}",`);
    valueLines.push(`    recordName: "${info.baseName}",`);
    valueLines.push(`    deserialize: ${info.deserializerName},`);
    valueLines.push(`  }),`);
    valueLines.push("};");
  }

  // Widened input aliases for external struct/record refs. Local types get
  // explicit `${Name}Input` interfaces; external refs reuse the imported branded
  // type through `WidenInput<…>` so no cross-program `Input` import is needed.
  // Emitted for both struct and record refs (so struct-only programs still get
  // them — hence no early return before this block).
  const aliases: { readonly alias: string; readonly typeName: string }[] = [];
  for (const ref of ctx.externalStructRefs.values()) {
    const info = externalStructInfo(ref, ctx);
    if (info) aliases.push({ alias: structInputName(ref, ctx), typeName: info.typeName });
  }
  for (const ref of ctx.externalRecordRefs.values()) {
    const info = externalRecordInfo(ref, ctx);
    if (info) aliases.push({ alias: recordInputName(ref, ctx), typeName: info.typeName });
  }
  const aliasLines = aliases
    .sort((a, b) => a.alias.localeCompare(b.alias))
    .map(({ alias, typeName }) => `export type ${alias} = ${ctx.widenInputAlias}<${typeName}>;`);

  const tail: string[] = [];
  if (valueLines.length > 0) tail.push("", ...valueLines);
  if (aliasLines.length > 0) tail.push("", ...aliasLines);
  return [...importLines, ...tail];
}

function isLocalStructRef(ref: StructRef, ctx: GenerationContext): boolean {
  if (ref.program !== null && ref.program !== ctx.programId) return false;
  return ctx.structsByKey.has(pathKey(ref.path));
}

function isLocalRecordRef(ref: RecordRef, ctx: GenerationContext): boolean {
  if (ref.program !== null && ref.program !== ctx.programId) return false;
  return ctx.recordsByKey.has(pathKey(ref.path));
}

function externalStructInfo(ref: StructRef, ctx: GenerationContext): ExternalRefInfo | null {
  const programId = ref.program;
  if (!programId || programId === ctx.programId) return null;
  return ctx.externalInfoByKey.get(externalRefKey(ref)) ?? null;
}

function externalRecordInfo(ref: RecordRef, ctx: GenerationContext): ExternalRefInfo | null {
  const programId = ref.program;
  if (!programId || programId === ctx.programId) return null;
  return ctx.externalInfoByKey.get(externalRefKey(ref)) ?? null;
}

function pathKey(path: readonly string[]): string {
  return path.join("::");
}

function externalRefKey(ref: StructRef | RecordRef): string {
  return `${ref.program ?? ""}:${pathKey(ref.path)}`;
}

function formatArgsObjectType(inputs: readonly AbiInput[], ctx: GenerationContext): string {
  const fields = inputs.map(
    (input) => `readonly ${input.name}: ${aleoTypeToInputBindingTs(input.ty, ctx)}`,
  );
  return `{ ${fields.join("; ")} }`;
}

function formatTransitionMethodParams(
  hasInputs: boolean,
  argsType: string,
  optionsType: "LocalExecutionOptions" | "OnChainExecutionOptions",
): string {
  return hasInputs ? `args: ${argsType}, options?: ${optionsType}` : `options?: ${optionsType}`;
}

function formatReturnType(outputs: readonly AbiOutput[], ctx: GenerationContext): string {
  if (outputs.length === 0) return "void";
  if (outputs.length === 1) return aleoTypeToOutputBindingTs(outputs[0]!.ty, ctx);
  return `[${outputs.map((o) => aleoTypeToOutputBindingTs(o.ty, ctx)).join(", ")}]`;
}

/**
 * Typed `outputs` field shape for on-chain results. Mirrors `formatReturnType`'s
 * arity rule, with two substitutions:
 *   - Record types (local + imported) and DynamicRecord → `EncryptedRecord<T>`.
 *   - Private / default-private plaintext outputs (Aleo emits these as value
 *     ciphertexts on chain) → `EncryptedValue<T>`.
 * Public plaintext outputs keep their decoded type.
 * Future entries are dropped from the result shape (they still occupy
 * positions in rawOutputs).
 */
function formatTypedOutputType(outputs: readonly AbiOutput[], ctx: GenerationContext): string {
  const visible = outputs.filter((o) => !isFutureOutput(o.ty));
  if (visible.length === 0) return "void";
  if (visible.length === 1) return typedOutputElementType(visible[0]!, ctx);
  return `[${visible.map((o) => typedOutputElementType(o, ctx)).join(", ")}]`;
}

function isFutureOutput(ty: AleoType): boolean {
  return typeof ty === "object" && ty !== null && "Future" in ty;
}

/**
 * A plaintext output appears as a value ciphertext on chain when its
 * visibility is not explicitly `Public`. Leo emits `mode: "None"` when no
 * visibility modifier was written (Leo's default is private). Both `"None"`
 * and `"Private"` produce `ciphertext1...` on chain.
 */
function isPrivatePlaintextOutput(output: AbiOutput): boolean {
  const ty = output.ty;
  if (typeof ty !== "object" || ty === null || !("Plaintext" in ty)) return false;
  return output.mode !== "Public";
}

function typedOutputElementType(output: AbiOutput, ctx: GenerationContext): string {
  const ty = output.ty;
  if (ty === "DynamicRecord") return "IdOnlyDynamicRecordHandle";
  if (typeof ty === "object" && ty !== null && "Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) {
      return `EncryptedRecord<${recordRefName(ty.Record)}>`;
    }
    const external = externalRecordInfo(ty.Record, ctx);
    return external
      ? `IdOnlyExternalRecordHandle<${external.typeName}>`
      : "IdOnlyExternalRecordHandle<LeoDynamicRecord>";
  }
  if (typeof ty === "object" && ty !== null && "Plaintext" in ty) {
    const decoded = plaintextToOutputBindingTs(ty.Plaintext, ctx);
    return isPrivatePlaintextOutput(output) ? `EncryptedValue<${decoded}>` : decoded;
  }
  return "unknown";
}

/**
 * Emit the projector function literal passed to settleTyped / expectAcceptedTyped.
 * Indexes rawOutputs by ORIGINAL ABI position (Future entries reserve their slot
 * in rawOutputs but contribute nothing to the typed result shape).
 *
 * Signature is `(rawOutputs, tpk) => TOutputs` regardless of whether `tpk` is
 * consumed. When the transition has at least one private plaintext output
 * (decoded as `EncryptedValue<T>` and requiring `tpk`), the parameter name is
 * `tpk`. Otherwise it's `_tpk` to keep `noUnusedParameters`-style checks quiet.
 */
function formatProjectorExpr(
  transition: TransitionABI,
  programId: string,
  ctx: GenerationContext,
): string {
  const visibleIndices: number[] = [];
  transition.outputs.forEach((output, idx) => {
    if (!isFutureOutput(output.ty)) visibleIndices.push(idx);
  });

  const transitionName = transition.name;
  const hasPrivatePlaintext = transition.outputs.some(isPrivatePlaintextOutput);
  const tpkParam = hasPrivatePlaintext ? "tpk" : "_tpk";
  const usesTransitions = transition.outputs.some((o) => projectorElementUsesTransitions(o, ctx));
  const transitionsParam = usesTransitions ? "transitions" : "_transitions";
  const inputCount = transition.inputs.length;

  if (visibleIndices.length === 0) {
    return `(_rawOutputs: readonly RawTransitionOutput[], ${tpkParam}: string, ${transitionsParam}: readonly ConfirmedTransitionRecord[]) => undefined as void`;
  }

  const rawAccess = (abiIndex: number): string =>
    `BaseContract.rawOutputAt(rawOutputs, "${programId}", "${transitionName}", ${abiIndex})`;

  const decodeForIndex = (abiIndex: number): string => {
    const output = transition.outputs[abiIndex]!;
    const access = rawAccess(abiIndex);
    return projectorElementExpr(
      access,
      output,
      programId,
      transitionName,
      abiIndex,
      inputCount,
      ctx,
    );
  };

  if (visibleIndices.length === 1) {
    const abiIndex = visibleIndices[0]!;
    return `(rawOutputs: readonly RawTransitionOutput[], ${tpkParam}: string, ${transitionsParam}: readonly ConfirmedTransitionRecord[]) => ${decodeForIndex(abiIndex)}`;
  }

  const tupleType = formatTypedOutputType(transition.outputs, ctx);
  const elems = visibleIndices.map(decodeForIndex);
  return `(rawOutputs: readonly RawTransitionOutput[], ${tpkParam}: string, ${transitionsParam}: readonly ConfirmedTransitionRecord[]) => ([${elems.join(", ")}] as ${tupleType})`;
}

/**
 * Whether the projector element for this output references the `transitions`
 * parameter — true for `dyn record` and any external `Record` (both id-only
 * constructors close over `transitions`). Local concrete records and
 * plaintext outputs don't reference `transitions`.
 */
function projectorElementUsesTransitions(output: AbiOutput, ctx: GenerationContext): boolean {
  const ty = output.ty;
  if (ty === "DynamicRecord") return true;
  if (typeof ty === "object" && ty !== null && "Record" in ty) {
    return !isLocalRecordRef(ty.Record, ctx);
  }
  return false;
}

function projectorElementExpr(
  rawExpr: string,
  output: AbiOutput,
  programId: string,
  transitionName: string,
  abiIndex: number,
  inputCount: number,
  ctx: GenerationContext,
): string {
  const ty = output.ty;
  const idOnlyAccess = `BaseContract.idOnlyRecordOutputAt(rawOutputs, "${programId}", "${transitionName}", ${abiIndex})`;
  if (ty === "DynamicRecord") {
    return `BaseContract.makeIdOnlyDynamicRecordHandle(${idOnlyAccess}, transitions)`;
  }
  if (typeof ty === "object" && ty !== null && "Record" in ty) {
    if (isLocalRecordRef(ty.Record, ctx)) {
      return `BaseContract.makeEncryptedRecord("${programId}", "${recordRefName(ty.Record)}", ${rawExpr}, deserialize${recordRefName(ty.Record)})`;
    }
    const external = externalRecordInfo(ty.Record, ctx);
    const typeArg = external?.typeName ?? "LeoDynamicRecord";
    return `BaseContract.makeIdOnlyExternalRecordHandle<${typeArg}>(${idOnlyAccess}, transitions)`;
  }
  if (typeof ty === "object" && ty !== null && "Plaintext" in ty) {
    if (isPrivatePlaintextOutput(output)) {
      // Global index = inputs.length + outputAbiIndex. Aleo's domain
      // separation places inputs first; verified by Step 0 devnode decrypt.
      const globalIndex = inputCount + abiIndex;
      const deserializer = plaintextDeserializerFn(ty.Plaintext, ctx);
      return `BaseContract.makeEncryptedValue(${rawExpr}, tpk, "${programId}", "${transitionName}", ${globalIndex}, ${deserializer})`;
    }
    return deserializePlaintextExpr(rawExpr, ty.Plaintext, ctx);
  }
  return rawExpr;
}

export function programIdToClassName(programId: string): string {
  const name = programId.replace(/\.aleo$/, "");
  return name
    .split(/[_\-.]/)
    .map(capitalize)
    .join("");
}

/**
 * Typechain file stems the emitter always writes besides per-program modules.
 * A program whose class name equals one of these would overwrite that file.
 */
const RESERVED_TYPECHAIN_FILE_STEMS: readonly string[] = ["BaseContract", "index"];

/**
 * Assert that every program id maps to a distinct typechain module file
 * (`${programIdToClassName(id)}.ts`) and that none collides with a reserved
 * emitter file (`BaseContract.ts`, `index.ts`).
 *
 * `programIdToClassName` is non-injective — it splits on `[_\-.]` and
 * CamelCases — so e.g. `foo_bar.aleo` and `foo__bar.aleo` both yield `FooBar`,
 * and `base_contract.aleo` yields `BaseContract`. The per-program emit loop
 * writes `${stem}.ts` with no cross-program dedup, so a collision silently
 * overwrites another program's bindings (or the runtime `BaseContract.ts`),
 * leaving the generated module set internally inconsistent.
 *
 * Comparison is case-insensitive: the common dev filesystems (macOS APFS,
 * Windows NTFS) are case-insensitive, so `Index.ts` would overwrite the barrel
 * `index.ts`, and two programs whose class names differ only by case (e.g.
 * `ab.aleo` → `Ab`, `a_b.aleo` → `AB`) would share one file. This guard turns
 * any such collision into a clear build-time `CodegenError` instead.
 */
export function assertTypechainModuleNamesUnique(programIds: readonly string[]): void {
  // Keyed by lower-cased stem (case-insensitive FS); value preserves the
  // original casing for the error message.
  const reserved = new Map<string, string>(
    RESERVED_TYPECHAIN_FILE_STEMS.map((stem) => [stem.toLowerCase(), stem]),
  );
  const seen = new Map<string, string>(); // lower stem -> first program id claiming it
  for (const programId of programIds) {
    const stem = programIdToClassName(programId);
    const key = stem.toLowerCase();
    const reservedStem = reserved.get(key);
    if (reservedStem !== undefined) {
      throw new CodegenError(
        `Program '${programId}' generates typechain/${stem}.ts, which collides with the reserved generated file '${reservedStem}.ts' (file names are compared case-insensitively). Rename the program (its id maps to the class name '${stem}').`,
        { programId, fileStem: stem, reservedFile: reservedStem, phase: "generate" },
      );
    }
    const existing = seen.get(key);
    if (existing !== undefined) {
      throw new CodegenError(
        `Programs '${existing}' and '${programId}' both generate typechain/${stem}.ts (file names are compared case-insensitively): their program ids map to the same module file. Rename one of them so each program maps to a distinct typechain module.`,
        { programId, conflictsWith: existing, fileStem: stem, phase: "generate" },
      );
    }
    seen.set(key, programId);
  }
}

/**
 * Derive a class name that does not collide with struct/record interface names
 * or the BaseContract imports emitted for this module. The latter also keeps
 * the `create${class}` factory clear of the imported `createRecordOutputMatcher`
 * (e.g. `record_output_matcher.aleo` → `RecordOutputMatcherContract`).
 */
export function resolveContractClassName(
  abi: ProgramABI,
  options: { readonly includeLeoValueImport?: boolean } = {},
): string {
  const base = programIdToClassName(abi.program);
  const typeNames = new Set<string>([
    ...reservedBaseContractImportNames(options.includeLeoValueImport ?? false),
    ...abi.structs.map((s) => pathToTsName(s.path)),
    ...abi.records.map((r) => pathToTsName(r.path)),
  ]);
  let candidate = base;
  while (typeNames.has(candidate)) {
    candidate += "Contract";
  }
  return candidate;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function isValidIdentifier(name: string): boolean {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name);
}

/**
 * snake_case -> camelCase for generated state property names. Leading underscores are
 * preserved (`_internal` -> `_internal`); only internal `_x` boundaries are camelCased.
 */
function toCamelCase(name: string): string {
  const lead = /^_+/.exec(name)?.[0] ?? "";
  const rest = name.slice(lead.length);
  const camel = rest.replace(/_+([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase());
  return lead + camel;
}

/**
 * Maps each mapping's original (Leo) name to the property key to emit on the
 * generated `mappings` object. Collision-safe: if two mappings camelCase to the
 * same key, every member of that collision group is emitted under its original
 * Leo name (quoted) so no two mappings produce a duplicate object key.
 */
function buildStatePropKeys(entries: readonly { readonly name: string }[]): Map<string, string> {
  const groups = new Map<string, string[]>(); // camelName -> original names
  for (const entry of entries) {
    const camel = toCamelCase(entry.name);
    const originals = groups.get(camel) ?? [];
    originals.push(entry.name);
    groups.set(camel, originals);
  }

  const propKeys = new Map<string, string>(); // original name -> emitted key token
  for (const [camel, originals] of groups) {
    if (originals.length > 1) {
      for (const original of originals) {
        propKeys.set(original, JSON.stringify(original));
      }
    } else {
      const original = originals[0]!;
      propKeys.set(original, isValidIdentifier(camel) ? camel : JSON.stringify(camel));
    }
  }
  return propKeys;
}

function buildMappingPropKeys(mappings: readonly MappingABI[]): Map<string, string> {
  return buildStatePropKeys(mappings);
}

function buildStoragePropKeys(
  storageVariables: readonly StorageVariableABI[],
): Map<string, string> {
  return buildStatePropKeys(storageVariables);
}

function indentLines(lines: readonly string[], indent: string): string[] {
  return lines.map((line) => (line === "" ? "" : `${indent}${line}`));
}
