// Auto-generated by @lionden/leo-compiler — do not edit
// Program: consumer.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext, type WidenInput as WidenInput_ } from "./BaseContract.js";
import { deserializeTokenInfo as deserializeRegistry_TokenInfo, serializeTokenInfo as serializeRegistry_TokenInfo, type TokenInfo as Registry_TokenInfo } from "./Registry.js";

export type Registry_TokenInfoInput = WidenInput_<Registry_TokenInfo>;

export interface WidenInput {
  readonly n: bigint;
}

export interface WidenInputInput {
  readonly n: bigint;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeWidenInput(value: WidenInputInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("n: " + BaseContract.serializeUInt(value.n, 64, BaseContract.childInputContext(context, "n")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeWidenInput(value: string): WidenInput {
  const _fields = BaseContract.parseStruct(value);
  return {
    n: BaseContract.parseBigInt(_fields["n"]!),
  };
}

// ---------------------------------------------------------------------------
// Consumer contract wrapper
// ---------------------------------------------------------------------------

export class Consumer extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("consumer.aleo", options);
  }

  readonly make = {
    locally: async (args: { readonly n: bigint }, options?: LocalExecutionOptions): Promise<WidenInput> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      const _result = await this.executeLocal("make", _args, options ?? {});
      return deserializeWidenInput(this.outputAt(_result, "make", 0));
    },

    failsLocally: async (args: { readonly n: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      await this.expectLocalFailure("make", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly n: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      return this.expectLocalFailure("make", _args, options ?? {});
    },

    submitted: async (args: { readonly n: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      return this.submitTransition("make", _args, options ?? {});
    },

    settled: async (args: { readonly n: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<WidenInput>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      return this.settleTyped("make", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "consumer.aleo", "make", 0), tpk, "consumer.aleo", "make", 1, (_p: string) => deserializeWidenInput(_p)));
    },

    accepted: async (args: { readonly n: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<WidenInput>>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      return this.expectAcceptedTyped("make", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "consumer.aleo", "make", 0), tpk, "consumer.aleo", "make", 1, (_p: string) => deserializeWidenInput(_p)));
    },

    rejected: async (args: { readonly n: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.n, 64, this.inputContext("make", "n")),
      ];
      return this.expectRejected("make", _args, options ?? {});
    },
  } as const;

  readonly relay = {
    locally: async (args: { readonly info: Registry_TokenInfoInput }, options?: LocalExecutionOptions): Promise<Registry_TokenInfo> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      const _result = await this.executeLocal("relay", _args, options ?? {});
      return deserializeRegistry_TokenInfo(this.outputAt(_result, "relay", 0));
    },

    failsLocally: async (args: { readonly info: Registry_TokenInfoInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      await this.expectLocalFailure("relay", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly info: Registry_TokenInfoInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      return this.expectLocalFailure("relay", _args, options ?? {});
    },

    submitted: async (args: { readonly info: Registry_TokenInfoInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      return this.submitTransition("relay", _args, options ?? {});
    },

    settled: async (args: { readonly info: Registry_TokenInfoInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Registry_TokenInfo>> | RejectedTransition> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      return this.settleTyped("relay", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "consumer.aleo", "relay", 0), tpk, "consumer.aleo", "relay", 1, (_p: string) => deserializeRegistry_TokenInfo(_p)));
    },

    accepted: async (args: { readonly info: Registry_TokenInfoInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Registry_TokenInfo>>> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      return this.expectAcceptedTyped("relay", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "consumer.aleo", "relay", 0), tpk, "consumer.aleo", "relay", 1, (_p: string) => deserializeRegistry_TokenInfo(_p)));
    },

    rejected: async (args: { readonly info: Registry_TokenInfoInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeRegistry_TokenInfo(args.info as Registry_TokenInfoInput, this.inputContext("relay", "info")),
      ];
      return this.expectRejected("relay", _args, options ?? {});
    },
  } as const;
}

export function createConsumer(options?: BaseContractOptions): Consumer {
  return new Consumer(options);
}
