// Auto-generated by @lionden/leo-compiler — do not edit
// Program: prov.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Sh_Env {
  readonly account: LeoAddress;
  readonly count: number;
}

export interface Sh_EnvInput {
  readonly account: AddressInput;
  readonly count: number;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeSh_Env(value: Sh_EnvInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("account: " + BaseContract.serializeAddress(value.account, BaseContract.childInputContext(context, "account")));
  fields.push("count: " + BaseContract.serializeUInt(value.count, 32, BaseContract.childInputContext(context, "count")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeSh_Env(value: string): Sh_Env {
  const _fields = BaseContract.parseStruct(value);
  return {
    account: BaseContract.parseAddress(_fields["account"]!),
    count: BaseContract.parseNumber(_fields["count"]!),
  };
}

// ---------------------------------------------------------------------------
// Prov contract wrapper
// ---------------------------------------------------------------------------

export class Prov extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("prov.aleo", options);
  }

  readonly envelope_echo = {
    locally: async (args: { readonly e: Sh_EnvInput }, options?: LocalExecutionOptions): Promise<Sh_Env> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      const _result = await this.executeLocal("envelope_echo", _args, options ?? {});
      return deserializeSh_Env(this.outputAt(_result, "envelope_echo", 0));
    },

    failsLocally: async (args: { readonly e: Sh_EnvInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      await this.expectLocalFailure("envelope_echo", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly e: Sh_EnvInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      return this.expectLocalFailure("envelope_echo", _args, options ?? {});
    },

    submitted: async (args: { readonly e: Sh_EnvInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      return this.submitTransition("envelope_echo", _args, options ?? {});
    },

    settled: async (args: { readonly e: Sh_EnvInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Sh_Env>> | RejectedTransition> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      return this.settleTyped("envelope_echo", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "prov.aleo", "envelope_echo", 0), tpk, "prov.aleo", "envelope_echo", 1, (_p: string) => deserializeSh_Env(_p)));
    },

    accepted: async (args: { readonly e: Sh_EnvInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Sh_Env>>> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      return this.expectAcceptedTyped("envelope_echo", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "prov.aleo", "envelope_echo", 0), tpk, "prov.aleo", "envelope_echo", 1, (_p: string) => deserializeSh_Env(_p)));
    },

    rejected: async (args: { readonly e: Sh_EnvInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeSh_Env(args.e as Sh_EnvInput, this.inputContext("envelope_echo", "e")),
      ];
      return this.expectRejected("envelope_echo", _args, options ?? {});
    },
  } as const;
}

export function createProv(options?: BaseContractOptions): Prov {
  return new Prov(options);
}
