// Auto-generated by @lionden/leo-compiler — do not edit
// Program: grid.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

export interface Cell {
  readonly value: number;
}

export interface Board {
  readonly cells: Cell[][];
  readonly turn: number;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeCell(value: Cell): string {
  const fields: string[] = [];
  fields.push("value: " + value.value.toString() + "u8");
  return "{ " + fields.join(", ") + " }";
}

export function deserializeCell(value: string): Cell {
  const _fields = BaseContract.parseStruct(value);
  return {
    value: BaseContract.parseNumber(_fields["value"]!),
  };
}

export function serializeBoard(value: Board): string {
  const fields: string[] = [];
  fields.push("cells: " + "[" + value.cells.map((e: any) => "[" + e.map((e: any) => serializeCell(e)).join(", ") + "]").join(", ") + "]");
  fields.push("turn: " + value.turn.toString() + "u8");
  return "{ " + fields.join(", ") + " }";
}

export function deserializeBoard(value: string): Board {
  const _fields = BaseContract.parseStruct(value);
  return {
    cells: BaseContract.parseArray(_fields["cells"]!).map((e: string) => BaseContract.parseArray(e).map((e: string) => deserializeCell(e))),
    turn: BaseContract.parseNumber(_fields["turn"]!),
  };
}

// ---------------------------------------------------------------------------
// Grid contract wrapper
// ---------------------------------------------------------------------------

export class Grid extends BaseContract {
  constructor() {
    super("grid.aleo");
  }

  async get_board(
    options?: LocalCallOptions,
  ): Promise<Board> {
    const _args: string[] = [
    ];
    const _result = await this.executeLocal("get_board", _args, options ?? {});
    return deserializeBoard(_result.outputs[0]!);
  }
  
  async get_boardBroadcast(
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
    ];
    return this.broadcast("get_board", _args, options ?? {});
  }

  async set_cell(
    board: Board,
    row: number,
    col: number,
    val: Cell,
    options?: LocalCallOptions,
  ): Promise<Board> {
    const _args: string[] = [
      serializeBoard(board),
      row.toString() + "u32",
      col.toString() + "u32",
      serializeCell(val),
    ];
    const _result = await this.executeLocal("set_cell", _args, options ?? {});
    return deserializeBoard(_result.outputs[0]!);
  }
  
  async set_cellBroadcast(
    board: Board,
    row: number,
    col: number,
    val: Cell,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      serializeBoard(board),
      row.toString() + "u32",
      col.toString() + "u32",
      serializeCell(val),
    ];
    return this.broadcast("set_cell", _args, options ?? {});
  }
}

export function createGrid(): Grid {
  return new Grid();
}
