// Auto-generated by @lionden/leo-compiler — do not edit
// Program: grid.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type BaseContractOptions, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Cell {
  readonly value: number;
}

export interface Board {
  readonly cells: ReadonlyArray<ReadonlyArray<Cell>>;
  readonly turn: number;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeCell(value: Cell, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("value: " + BaseContract.serializeUInt(value.value, 8, BaseContract.childInputContext(context, "value")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeCell(value: string): Cell {
  const _fields = BaseContract.parseStruct(value);
  return {
    value: BaseContract.parseNumber(_fields["value"]!),
  };
}

export function serializeBoard(value: Board, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("cells: " + BaseContract.serializeArray(value.cells, BaseContract.childInputContext(context, "cells"), (e: unknown, context: TransitionInputContext | undefined) => BaseContract.serializeArray(e, context, (e: unknown, context: TransitionInputContext | undefined) => serializeCell(e as Cell, context))));
  fields.push("turn: " + BaseContract.serializeUInt(value.turn, 8, BaseContract.childInputContext(context, "turn")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeBoard(value: string): Board {
  const _fields = BaseContract.parseStruct(value);
  return {
    cells: BaseContract.parseArray(_fields["cells"]!).map((e: string) => BaseContract.parseArray(e).map((e: string) => deserializeCell(e))),
    turn: BaseContract.parseNumber(_fields["turn"]!),
  };
}

// ---------------------------------------------------------------------------
// Grid contract wrapper
// ---------------------------------------------------------------------------

export class Grid extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("grid.aleo", options);
  }

  readonly get_board = {
    locally: async (options?: LocalExecutionOptions): Promise<Board> => {
      const _args: string[] = [
      ];
      const _result = await this.executeLocal("get_board", _args, options ?? {});
      return deserializeBoard(this.outputAt(_result, "get_board", 0));
    },

    failsLocally: async (options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
      ];
      await this.expectLocalFailure("get_board", _args, options ?? {});
    },

    captureLocalFailure: async (options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
      ];
      return this.expectLocalFailure("get_board", _args, options ?? {});
    },

    submitted: async (options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
      ];
      return this.submitTransition("get_board", _args, options ?? {});
    },

    settled: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Board>> | RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.settleTyped("get_board", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "grid.aleo", "get_board", 0), tpk, "grid.aleo", "get_board", 0, (_p: string) => deserializeBoard(_p)));
    },

    accepted: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Board>>> => {
      const _args: string[] = [
      ];
      return this.expectAcceptedTyped("get_board", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "grid.aleo", "get_board", 0), tpk, "grid.aleo", "get_board", 0, (_p: string) => deserializeBoard(_p)));
    },

    rejected: async (options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.expectRejected("get_board", _args, options ?? {});
    },
  } as const;

  readonly set_cell = {
    locally: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: LocalExecutionOptions): Promise<Board> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      const _result = await this.executeLocal("set_cell", _args, options ?? {});
      return deserializeBoard(this.outputAt(_result, "set_cell", 0));
    },

    failsLocally: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      await this.expectLocalFailure("set_cell", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      return this.expectLocalFailure("set_cell", _args, options ?? {});
    },

    submitted: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      return this.submitTransition("set_cell", _args, options ?? {});
    },

    settled: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Board>> | RejectedTransition> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      return this.settleTyped("set_cell", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "grid.aleo", "set_cell", 0), tpk, "grid.aleo", "set_cell", 4, (_p: string) => deserializeBoard(_p)));
    },

    accepted: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Board>>> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      return this.expectAcceptedTyped("set_cell", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "grid.aleo", "set_cell", 0), tpk, "grid.aleo", "set_cell", 4, (_p: string) => deserializeBoard(_p)));
    },

    rejected: async (args: { readonly board: Board; readonly row: number; readonly col: number; readonly val: Cell }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeBoard(args.board as Board, this.inputContext("set_cell", "board")),
        BaseContract.serializeUInt(args.row, 32, this.inputContext("set_cell", "row")),
        BaseContract.serializeUInt(args.col, 32, this.inputContext("set_cell", "col")),
        serializeCell(args.val as Cell, this.inputContext("set_cell", "val")),
      ];
      return this.expectRejected("set_cell", _args, options ?? {});
    },
  } as const;
}

export function createGrid(options?: BaseContractOptions): Grid {
  return new Grid(options);
}
