// Auto-generated by @lionden/leo-compiler — do not edit
// Program: dex.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type BaseContractOptions, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Pair {
  readonly token_a: LeoAddress;
  readonly token_b: LeoAddress;
  readonly reserve_a: bigint;
  readonly reserve_b: bigint;
}

export interface LPToken {
  readonly owner: LeoAddress;
  readonly amount: bigint;
  readonly pair_id: LeoField;
  readonly _nonce: LeoGroup;
}

export interface DexStorage {
  readonly admin: LeoAddress;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializePair(value: Pair, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("token_a: " + BaseContract.serializeAddress(value.token_a, BaseContract.childInputContext(context, "token_a")));
  fields.push("token_b: " + BaseContract.serializeAddress(value.token_b, BaseContract.childInputContext(context, "token_b")));
  fields.push("reserve_a: " + BaseContract.serializeUInt(value.reserve_a, 128, BaseContract.childInputContext(context, "reserve_a")));
  fields.push("reserve_b: " + BaseContract.serializeUInt(value.reserve_b, 128, BaseContract.childInputContext(context, "reserve_b")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializePair(value: string): Pair {
  const _fields = BaseContract.parseStruct(value);
  return {
    token_a: BaseContract.parseAddress(_fields["token_a"]!),
    token_b: BaseContract.parseAddress(_fields["token_b"]!),
    reserve_a: BaseContract.parseBigInt(_fields["reserve_a"]!),
    reserve_b: BaseContract.parseBigInt(_fields["reserve_b"]!),
  };
}

export function serializeLPToken(value: LPToken, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];
  if (typeof _raw === "string") return _raw;
  const fields: string[] = [];
  fields.push("owner: " + BaseContract.serializeAddress(value.owner, BaseContract.childInputContext(context, "owner")));
  fields.push("amount: " + BaseContract.serializeUInt(value.amount, 64, BaseContract.childInputContext(context, "amount")));
  fields.push("pair_id: " + BaseContract.serializeField(value.pair_id, BaseContract.childInputContext(context, "pair_id")));
  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeLPToken(value: string): LPToken {
  const _fields = BaseContract.parseStruct(value);
  const _record: LPToken = {
    owner: BaseContract.parseAddress(_fields["owner"]!),
    amount: BaseContract.parseBigInt(_fields["amount"]!),
    pair_id: BaseContract.parseField(_fields["pair_id"]!),
    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),
  };
  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });
  return _record;
}

export async function decryptLPToken(ciphertext: string, key: RecordDecryptionKey): Promise<LPToken> {
  return BaseContract.decryptRecord(ciphertext, key, deserializeLPToken);
}

// ---------------------------------------------------------------------------
// Dex contract wrapper
// ---------------------------------------------------------------------------

export class Dex extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("dex.aleo", options);
  }

  readonly add_liquidity = {
    locally: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: LocalExecutionOptions): Promise<[LPToken, void]> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      const _result = await this.executeLocal("add_liquidity", _args, options ?? {});
      const _decoded: [LPToken, void] = [deserializeLPToken(this.outputAt(_result, "add_liquidity", 0)), undefined as any];
      return _decoded;
    },

    failsLocally: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      await this.expectLocalFailure("add_liquidity", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      return this.expectLocalFailure("add_liquidity", _args, options ?? {});
    },

    submitted: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      return this.submitTransition("add_liquidity", _args, options ?? {});
    },

    settled: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<LPToken>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      return this.settleTyped("add_liquidity", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string) => BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "dex.aleo", "add_liquidity", 0), deserializeLPToken));
    },

    accepted: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<LPToken>>> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      return this.expectAcceptedTyped("add_liquidity", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string) => BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "dex.aleo", "add_liquidity", 0), deserializeLPToken));
    },

    rejected: async (args: { readonly pair_id: FieldInput; readonly amount_a: bigint; readonly amount_b: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("add_liquidity", "pair_id")),
        BaseContract.serializeUInt(args.amount_a, 128, this.inputContext("add_liquidity", "amount_a")),
        BaseContract.serializeUInt(args.amount_b, 128, this.inputContext("add_liquidity", "amount_b")),
      ];
      return this.expectRejected("add_liquidity", _args, options ?? {});
    },
  } as const;

  readonly remove_liquidity = {
    locally: async (args: { readonly lp_token: LPToken }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      const _result = await this.executeLocal("remove_liquidity", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly lp_token: LPToken }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      await this.expectLocalFailure("remove_liquidity", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly lp_token: LPToken }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      return this.expectLocalFailure("remove_liquidity", _args, options ?? {});
    },

    submitted: async (args: { readonly lp_token: LPToken }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      return this.submitTransition("remove_liquidity", _args, options ?? {});
    },

    settled: async (args: { readonly lp_token: LPToken }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      return this.settleTyped("remove_liquidity", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly lp_token: LPToken }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      return this.expectAcceptedTyped("remove_liquidity", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly lp_token: LPToken }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeLPToken(args.lp_token as LPToken, this.inputContext("remove_liquidity", "lp_token")),
      ];
      return this.expectRejected("remove_liquidity", _args, options ?? {});
    },
  } as const;

  readonly swap = {
    locally: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: LocalExecutionOptions): Promise<bigint> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      const _result = await this.executeLocal("swap", _args, options ?? {});
      return BaseContract.parseBigInt(this.outputAt(_result, "swap", 0));
    },

    failsLocally: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      await this.expectLocalFailure("swap", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      return this.expectLocalFailure("swap", _args, options ?? {});
    },

    submitted: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      return this.submitTransition("swap", _args, options ?? {});
    },

    settled: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<bigint>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      return this.settleTyped("swap", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "dex.aleo", "swap", 0), tpk, "dex.aleo", "swap", 2, BaseContract.parseBigInt));
    },

    accepted: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<bigint>>> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      return this.expectAcceptedTyped("swap", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "dex.aleo", "swap", 0), tpk, "dex.aleo", "swap", 2, BaseContract.parseBigInt));
    },

    rejected: async (args: { readonly pair_id: FieldInput; readonly amount_in: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeField(args.pair_id, this.inputContext("swap", "pair_id")),
        BaseContract.serializeUInt(args.amount_in, 128, this.inputContext("swap", "amount_in")),
      ];
      return this.expectRejected("swap", _args, options ?? {});
    },
  } as const;

  async getPairs(key: FieldInput): Promise<Pair | null> {
    const _result = await this.queryMapping("pairs", BaseContract.serializeField(key, { programId: this.programId, input: "pairs key" }));
    if (_result === null) return null;
    return deserializePair(_result);
  }

  async getTotal_supply(key: FieldInput): Promise<bigint | null> {
    const _result = await this.queryMapping("total_supply", BaseContract.serializeField(key, { programId: this.programId, input: "total_supply key" }));
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }
}

export function createDex(options?: BaseContractOptions): Dex {
  return new Dex(options);
}
