// Auto-generated by @lionden/leo-compiler — do not edit
// Program: proxy.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// Proxy contract wrapper
// ---------------------------------------------------------------------------

export class Proxy extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("proxy.aleo", options);
  }

  readonly forward = {
    locally: async (record: DynamicRecordInput, options?: LocalExecutionOptions): Promise<LeoDynamicRecord> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      const _result = await this.executeLocal("forward", _args, options ?? {});
      return BaseContract.parseDynamicRecord(this.outputAt(_result, "forward", 0));
    },

    failsLocally: async (record: DynamicRecordInput, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      await this.expectLocalFailure("forward", _args, options ?? {});
    },

    captureLocalFailure: async (record: DynamicRecordInput, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      return this.expectLocalFailure("forward", _args, options ?? {});
    },

    submitted: async (record: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      return this.submitTransition("forward", _args, options ?? {});
    },

    settled: async (record: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<IdOnlyDynamicRecordHandle> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      return this.settleTyped("forward", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward", 0), transitions, this.sourceProgramId, this.programId));
    },

    accepted: async (record: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<IdOnlyDynamicRecordHandle>> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      return this.expectAcceptedTyped("forward", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward", 0), transitions, this.sourceProgramId, this.programId));
    },

    rejected: async (record: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(record, this.inputContext("forward", "record")),
      ];
      return this.expectRejected("forward", _args, options ?? {});
    },
  } as const;

  readonly forward_pair = {
    locally: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: LocalExecutionOptions): Promise<[LeoDynamicRecord, LeoDynamicRecord]> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      const _result = await this.executeLocal("forward_pair", _args, options ?? {});
      const _decoded: [LeoDynamicRecord, LeoDynamicRecord] = [BaseContract.parseDynamicRecord(this.outputAt(_result, "forward_pair", 0)), BaseContract.parseDynamicRecord(this.outputAt(_result, "forward_pair", 1))];
      return _decoded;
    },

    failsLocally: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      await this.expectLocalFailure("forward_pair", _args, options ?? {});
    },

    captureLocalFailure: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      return this.expectLocalFailure("forward_pair", _args, options ?? {});
    },

    submitted: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      return this.submitTransition("forward_pair", _args, options ?? {});
    },

    settled: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<[IdOnlyDynamicRecordHandle, IdOnlyDynamicRecordHandle]> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      return this.settleTyped("forward_pair", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, transitions: readonly ConfirmedTransitionRecord[]) => ([BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward_pair", 0), transitions, this.sourceProgramId, this.programId), BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward_pair", 1), transitions, this.sourceProgramId, this.programId)] as [IdOnlyDynamicRecordHandle, IdOnlyDynamicRecordHandle]));
    },

    accepted: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<[IdOnlyDynamicRecordHandle, IdOnlyDynamicRecordHandle]>> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      return this.expectAcceptedTyped("forward_pair", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, transitions: readonly ConfirmedTransitionRecord[]) => ([BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward_pair", 0), transitions, this.sourceProgramId, this.programId), BaseContract.makeIdOnlyDynamicRecordHandle(BaseContract.idOnlyRecordOutputAt(rawOutputs, this.programId, "forward_pair", 1), transitions, this.sourceProgramId, this.programId)] as [IdOnlyDynamicRecordHandle, IdOnlyDynamicRecordHandle]));
    },

    rejected: async (a: DynamicRecordInput, b: DynamicRecordInput, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeDynamicRecord(a, this.inputContext("forward_pair", "a")),
        BaseContract.serializeDynamicRecord(b, this.inputContext("forward_pair", "b")),
      ];
      return this.expectRejected("forward_pair", _args, options ?? {});
    },
  } as const;
}

export function createProxy(options?: BaseContractOptions): Proxy {
  return new Proxy(options);
}
