// Auto-generated by @lionden/leo-compiler — do not edit
// Program: proxy.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// Proxy contract wrapper
// ---------------------------------------------------------------------------

export class Proxy extends BaseContract {
  constructor() {
    super("proxy.aleo");
  }

  async forward(
    record: string,
    options?: LocalCallOptions,
  ): Promise<string> {
    const _args: string[] = [
      record,
    ];
    const _result = await this.executeLocal("forward", _args, options ?? {});
    return _result.outputs[0]!;
  }

  async forwardBroadcast(
    record: string,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      record,
    ];
    return this.broadcast("forward", _args, options ?? {});
  }

  async forward_pair(
    a: string,
    b: string,
    options?: LocalCallOptions,
  ): Promise<[string, string]> {
    const _args: string[] = [
      a,
      b,
    ];
    const _result = await this.executeLocal("forward_pair", _args, options ?? {});
    const _decoded: [string, string] = [_result.outputs[0]!, _result.outputs[1]!];
    return _decoded;
  }

  async forward_pairBroadcast(
    a: string,
    b: string,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      a,
      b,
    ];
    return this.broadcast("forward_pair", _args, options ?? {});
  }
}

export function createProxy(): Proxy {
  return new Proxy();
}
