// Auto-generated by @lionden/leo-compiler — do not edit
// Program: collisions.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Foo {
  readonly id: LeoField;
  readonly roots: ReadonlyArray<LeoField>;
}

export interface Foo_Input {
  readonly id: FieldInput;
  readonly roots: ReadonlyArray<FieldInput>;
}

export interface FooInput {
  readonly value: bigint;
}

export interface FooInputInput {
  readonly value: bigint;
}

export interface Field {
  readonly x: LeoField;
}

export interface Field_Input {
  readonly x: FieldInput;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeFoo(value: Foo_Input, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("id: " + BaseContract.serializeField(value.id, BaseContract.childInputContext(context, "id")));
  fields.push("roots: " + BaseContract.serializeArray(value.roots, BaseContract.childInputContext(context, "roots"), (e: unknown, context: TransitionInputContext | undefined) => BaseContract.serializeField(e, context)));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeFoo(value: string): Foo {
  const _fields = BaseContract.parseStruct(value);
  return {
    id: BaseContract.parseField(_fields["id"]!),
    roots: BaseContract.parseArray(_fields["roots"]!).map((e: string) => BaseContract.parseField(e)),
  };
}

export function serializeFooInput(value: FooInputInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("value: " + BaseContract.serializeUInt(value.value, 64, BaseContract.childInputContext(context, "value")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeFooInput(value: string): FooInput {
  const _fields = BaseContract.parseStruct(value);
  return {
    value: BaseContract.parseBigInt(_fields["value"]!),
  };
}

export function serializeField(value: Field_Input, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("x: " + BaseContract.serializeField(value.x, BaseContract.childInputContext(context, "x")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeField(value: string): Field {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseField(_fields["x"]!),
  };
}

// ---------------------------------------------------------------------------
// Collisions contract wrapper
// ---------------------------------------------------------------------------

export class Collisions extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("collisions.aleo", options);
  }

  readonly submit = {
    locally: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: LocalExecutionOptions): Promise<LeoField> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      const _result = await this.executeLocal("submit", _args, options ?? {});
      return BaseContract.parseField(this.outputAt(_result, "submit", 0));
    },

    failsLocally: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      await this.expectLocalFailure("submit", _args, options ?? {});
    },

    captureLocalFailure: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      return this.expectLocalFailure("submit", _args, options ?? {});
    },

    submitted: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      return this.submitTransition("submit", _args, options ?? {});
    },

    settled: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<LeoField>> | RejectedTransition> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      return this.settleTyped("submit", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "collisions.aleo", "submit", 0), tpk, "collisions.aleo", "submit", 3, BaseContract.parseField));
    },

    accepted: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<LeoField>>> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      return this.expectAcceptedTyped("submit", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "collisions.aleo", "submit", 0), tpk, "collisions.aleo", "submit", 3, BaseContract.parseField));
    },

    rejected: async (a: Foo_Input, b: FooInputInput, c: Field_Input, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeFoo(a as Foo_Input, this.inputContext("submit", "a")),
        serializeFooInput(b as FooInputInput, this.inputContext("submit", "b")),
        serializeField(c as Field_Input, this.inputContext("submit", "c")),
      ];
      return this.expectRejected("submit", _args, options ?? {});
    },
  } as const;

  readonly mappings = {
    byFoo: {
      contains: async (key: Foo_Input): Promise<boolean> => {
        return this.mappingContains("by_foo", serializeFoo(key as Foo_Input, { programId: this.programId, input: "by_foo key" }));
      },
      get: async (key: Foo_Input): Promise<bigint> => {
        const _result = await this.requireMappingRaw("by_foo", serializeFoo(key as Foo_Input, { programId: this.programId, input: "by_foo key" }));
        return BaseContract.parseBigInt(_result);
      },
      getOrUse: async (key: Foo_Input, def: bigint): Promise<bigint> => {
        const _result = await this.queryMapping("by_foo", serializeFoo(key as Foo_Input, { programId: this.programId, input: "by_foo key" }));
        if (_result === null) return def;
        return BaseContract.parseBigInt(_result);
      },
      tryGet: async (key: Foo_Input): Promise<bigint | null> => {
        const _result = await this.queryMapping("by_foo", serializeFoo(key as Foo_Input, { programId: this.programId, input: "by_foo key" }));
        if (_result === null) return null;
        return BaseContract.parseBigInt(_result);
      },
    },
  } as const;
}

export function createCollisions(options?: BaseContractOptions): Collisions {
  return new Collisions(options);
}
