// Auto-generated by @lionden/leo-compiler — do not edit
// Program: stable_token.aleo

import { BaseContract, Leo, bindDynamicRecordHelperProgram, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Token {
  readonly owner: LeoAddress;
  readonly amount: bigint;
  readonly _version: number;
  readonly _nonce: LeoGroup;
}

export interface TokenInput {
  readonly owner: AddressInput;
  readonly amount: bigint;
  readonly _version: number;
  readonly _nonce: GroupInput;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeToken(value: TokenInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];
  if (typeof _raw === "string") return _raw;
  const fields: string[] = [];
  fields.push("amount: " + BaseContract.serializeUInt(value.amount, 128, BaseContract.childInputContext(context, "amount")));
  fields.push("_version: " + BaseContract.serializeUInt(value._version, 8, BaseContract.childInputContext(context, "_version")));
  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeToken(value: string): Token {
  const _fields = BaseContract.parseStruct(value);
  const _record: Token = {
    owner: BaseContract.parseAddress(_fields["owner"]!),
    amount: BaseContract.parseBigInt(_fields["amount"]!),
    _version: BaseContract.parseNumber(_fields["_version"]!),
    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),
  };
  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });
  return _record;
}

export async function decryptToken(ciphertext: string, key: RecordDecryptionKey): Promise<Token> {
  return BaseContract.decryptRecord(ciphertext, key, deserializeToken);
}

// ---------------------------------------------------------------------------
// Interface conversion helpers
// ---------------------------------------------------------------------------

function _asPoolTokenImpl(value: TokenInput): LeoDynamicRecord {
  return Leo.dynamicRecord(value, {
    owner: "address.private" as const,
    amount: "u128.private" as const,
    _version: "u8.public" as const,
    _nonce: "group.public" as const,
  } as const);
}
export const asPoolToken = Object.assign(_asPoolTokenImpl, {
  output: createRecordOutputMatcher<Token>({
    program: "stable_token.aleo",
    recordName: "Token",
    deserialize: deserializeToken,
  }),
  forProgram(programId: string) {
    return bindDynamicRecordHelperProgram(_asPoolTokenImpl, asPoolToken.output, programId);
  },
});

// ---------------------------------------------------------------------------
// StableToken contract wrapper
// ---------------------------------------------------------------------------

export class StableToken extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("stable_token.aleo", options);
  }

  readonly mint_private = {
    locally: async (receiver: AddressInput, amount: bigint, options?: LocalExecutionOptions): Promise<Token> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      const _result = await this.executeLocal("mint_private", _args, options ?? {});
      return deserializeToken(this.outputAt(_result, "mint_private", 0));
    },

    failsLocally: async (receiver: AddressInput, amount: bigint, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      await this.expectLocalFailure("mint_private", _args, options ?? {});
    },

    captureLocalFailure: async (receiver: AddressInput, amount: bigint, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      return this.expectLocalFailure("mint_private", _args, options ?? {});
    },

    submitted: async (receiver: AddressInput, amount: bigint, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      return this.submitTransition("mint_private", _args, options ?? {});
    },

    settled: async (receiver: AddressInput, amount: bigint, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      return this.settleTyped("mint_private", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedRecord(this.programId, "Token", BaseContract.rawOutputAt(rawOutputs, this.programId, "mint_private", 0), deserializeToken, this.sourceProgramId));
    },

    accepted: async (receiver: AddressInput, amount: bigint, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      return this.expectAcceptedTyped("mint_private", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedRecord(this.programId, "Token", BaseContract.rawOutputAt(rawOutputs, this.programId, "mint_private", 0), deserializeToken, this.sourceProgramId));
    },

    rejected: async (receiver: AddressInput, amount: bigint, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(amount, 128, this.inputContext("mint_private", "amount")),
      ];
      return this.expectRejected("mint_private", _args, options ?? {});
    },
  } as const;
}

export function createStableToken(options?: BaseContractOptions): StableToken {
  return new StableToken(options);
}
