// Auto-generated by @lionden/leo-compiler — do not edit
// Program: geo.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

export interface Point {
  readonly x: number;
  readonly y: number;
}

export interface Line {
  readonly start: Point;
  readonly end: Point;
}

export interface Triangle {
  readonly a: Line;
  readonly b: Line;
  readonly c: Line;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializePoint(value: Point): string {
  const fields: string[] = [];
  fields.push("x: " + value.x.toString() + "i32");
  fields.push("y: " + value.y.toString() + "i32");
  return "{ " + fields.join(", ") + " }";
}

export function deserializePoint(value: string): Point {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
    y: BaseContract.parseNumber(_fields["y"]!),
  };
}

export function serializeLine(value: Line): string {
  const fields: string[] = [];
  fields.push("start: " + serializePoint(value.start));
  fields.push("end: " + serializePoint(value.end));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeLine(value: string): Line {
  const _fields = BaseContract.parseStruct(value);
  return {
    start: deserializePoint(_fields["start"]!),
    end: deserializePoint(_fields["end"]!),
  };
}

export function serializeTriangle(value: Triangle): string {
  const fields: string[] = [];
  fields.push("a: " + serializeLine(value.a));
  fields.push("b: " + serializeLine(value.b));
  fields.push("c: " + serializeLine(value.c));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeTriangle(value: string): Triangle {
  const _fields = BaseContract.parseStruct(value);
  return {
    a: deserializeLine(_fields["a"]!),
    b: deserializeLine(_fields["b"]!),
    c: deserializeLine(_fields["c"]!),
  };
}

// ---------------------------------------------------------------------------
// Geo contract wrapper
// ---------------------------------------------------------------------------

export class Geo extends BaseContract {
  constructor() {
    super("geo.aleo");
  }

  async get_triangle(
    options?: LocalCallOptions,
  ): Promise<Triangle> {
    const _args: string[] = [
    ];
    const _result = await this.executeLocal("get_triangle", _args, options ?? {});
    return deserializeTriangle(_result.outputs[0]!);
  }
  
  async get_triangleBroadcast(
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
    ];
    return this.broadcast("get_triangle", _args, options ?? {});
  }

  async get_line(
    triangle: Triangle,
    options?: LocalCallOptions,
  ): Promise<Line> {
    const _args: string[] = [
      serializeTriangle(triangle),
    ];
    const _result = await this.executeLocal("get_line", _args, options ?? {});
    return deserializeLine(_result.outputs[0]!);
  }
  
  async get_lineBroadcast(
    triangle: Triangle,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      serializeTriangle(triangle),
    ];
    return this.broadcast("get_line", _args, options ?? {});
  }
}

export function createGeo(): Geo {
  return new Geo();
}
