// Auto-generated by @lionden/leo-compiler — do not edit
// Program: geo.aleo

import { BaseContract, type AddressInput, type DynamicRecordInput, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Point {
  readonly x: number;
  readonly y: number;
}

export interface Line {
  readonly start: Point;
  readonly end: Point;
}

export interface Triangle {
  readonly a: Line;
  readonly b: Line;
  readonly c: Line;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializePoint(value: Point, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("x: " + BaseContract.serializeInt(value.x, 32, BaseContract.childInputContext(context, "x")));
  fields.push("y: " + BaseContract.serializeInt(value.y, 32, BaseContract.childInputContext(context, "y")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializePoint(value: string): Point {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
    y: BaseContract.parseNumber(_fields["y"]!),
  };
}

export function serializeLine(value: Line, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("start: " + serializePoint(value.start as Point, BaseContract.childInputContext(context, "start")));
  fields.push("end: " + serializePoint(value.end as Point, BaseContract.childInputContext(context, "end")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeLine(value: string): Line {
  const _fields = BaseContract.parseStruct(value);
  return {
    start: deserializePoint(_fields["start"]!),
    end: deserializePoint(_fields["end"]!),
  };
}

export function serializeTriangle(value: Triangle, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("a: " + serializeLine(value.a as Line, BaseContract.childInputContext(context, "a")));
  fields.push("b: " + serializeLine(value.b as Line, BaseContract.childInputContext(context, "b")));
  fields.push("c: " + serializeLine(value.c as Line, BaseContract.childInputContext(context, "c")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeTriangle(value: string): Triangle {
  const _fields = BaseContract.parseStruct(value);
  return {
    a: deserializeLine(_fields["a"]!),
    b: deserializeLine(_fields["b"]!),
    c: deserializeLine(_fields["c"]!),
  };
}

// ---------------------------------------------------------------------------
// Geo contract wrapper
// ---------------------------------------------------------------------------

export class Geo extends BaseContract {
  constructor() {
    super("geo.aleo");
  }

  readonly get_triangle = {
    locally: async (options?: LocalExecutionOptions): Promise<Triangle> => {
      const _args: string[] = [
      ];
      const _result = await this.executeLocal("get_triangle", _args, options ?? {});
      return deserializeTriangle(this.outputAt(_result, "get_triangle", 0));
    },

    failsLocally: async (options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
      ];
      await this.expectLocalFailure("get_triangle", _args, options ?? {});
    },

    captureLocalFailure: async (options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
      ];
      return this.expectLocalFailure("get_triangle", _args, options ?? {});
    },

    submitted: async (options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
      ];
      return this.submitTransition("get_triangle", _args, options ?? {});
    },

    settled: async (options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
      ];
      return this.settleTransition("get_triangle", _args, options ?? {});
    },

    accepted: async (options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
      ];
      return this.expectAccepted("get_triangle", _args, options ?? {});
    },

    rejected: async (options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
      ];
      return this.expectRejected("get_triangle", _args, options ?? {});
    },
  } as const;

  readonly get_line = {
    locally: async (args: { readonly triangle: Triangle }, options?: LocalExecutionOptions): Promise<Line> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      const _result = await this.executeLocal("get_line", _args, options ?? {});
      return deserializeLine(this.outputAt(_result, "get_line", 0));
    },

    failsLocally: async (args: { readonly triangle: Triangle }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      await this.expectLocalFailure("get_line", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly triangle: Triangle }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      return this.expectLocalFailure("get_line", _args, options ?? {});
    },

    submitted: async (args: { readonly triangle: Triangle }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      return this.submitTransition("get_line", _args, options ?? {});
    },

    settled: async (args: { readonly triangle: Triangle }, options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      return this.settleTransition("get_line", _args, options ?? {});
    },

    accepted: async (args: { readonly triangle: Triangle }, options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      return this.expectAccepted("get_line", _args, options ?? {});
    },

    rejected: async (args: { readonly triangle: Triangle }, options?: OnChainExecutionOptions): Promise<SettledTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as Triangle, this.inputContext("get_line", "triangle")),
      ];
      return this.expectRejected("get_line", _args, options ?? {});
    },
  } as const;
}

export function createGeo(): Geo {
  return new Geo();
}
