// Auto-generated by @lionden/leo-compiler — do not edit
// Program: geo.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Point {
  readonly x: number;
  readonly y: number;
}

export interface PointInput {
  readonly x: number;
  readonly y: number;
}

export interface Line {
  readonly start: Point;
  readonly end: Point;
}

export interface LineInput {
  readonly start: PointInput;
  readonly end: PointInput;
}

export interface Triangle {
  readonly a: Line;
  readonly b: Line;
  readonly c: Line;
}

export interface TriangleInput {
  readonly a: LineInput;
  readonly b: LineInput;
  readonly c: LineInput;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializePoint(value: PointInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("x: " + BaseContract.serializeInt(value.x, 32, BaseContract.childInputContext(context, "x")));
  fields.push("y: " + BaseContract.serializeInt(value.y, 32, BaseContract.childInputContext(context, "y")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializePoint(value: string): Point {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
    y: BaseContract.parseNumber(_fields["y"]!),
  };
}

export function serializeLine(value: LineInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("start: " + serializePoint(value.start as PointInput, BaseContract.childInputContext(context, "start")));
  fields.push("end: " + serializePoint(value.end as PointInput, BaseContract.childInputContext(context, "end")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeLine(value: string): Line {
  const _fields = BaseContract.parseStruct(value);
  return {
    start: deserializePoint(_fields["start"]!),
    end: deserializePoint(_fields["end"]!),
  };
}

export function serializeTriangle(value: TriangleInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("a: " + serializeLine(value.a as LineInput, BaseContract.childInputContext(context, "a")));
  fields.push("b: " + serializeLine(value.b as LineInput, BaseContract.childInputContext(context, "b")));
  fields.push("c: " + serializeLine(value.c as LineInput, BaseContract.childInputContext(context, "c")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeTriangle(value: string): Triangle {
  const _fields = BaseContract.parseStruct(value);
  return {
    a: deserializeLine(_fields["a"]!),
    b: deserializeLine(_fields["b"]!),
    c: deserializeLine(_fields["c"]!),
  };
}

// ---------------------------------------------------------------------------
// Geo contract wrapper
// ---------------------------------------------------------------------------

export class Geo extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("geo.aleo", options);
  }

  readonly get_triangle = {
    locally: async (options?: LocalExecutionOptions): Promise<Triangle> => {
      const _args: string[] = [
      ];
      const _result = await this.executeLocal("get_triangle", _args, options ?? {});
      return deserializeTriangle(this.outputAt(_result, "get_triangle", 0));
    },

    failsLocally: async (options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
      ];
      await this.expectLocalFailure("get_triangle", _args, options ?? {});
    },

    captureLocalFailure: async (options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
      ];
      return this.expectLocalFailure("get_triangle", _args, options ?? {});
    },

    submitted: async (options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
      ];
      return this.submitTransition("get_triangle", _args, options ?? {});
    },

    settled: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Triangle>> | RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.settleTyped("get_triangle", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "geo.aleo", "get_triangle", 0), tpk, "geo.aleo", "get_triangle", 0, (_p: string) => deserializeTriangle(_p)));
    },

    accepted: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Triangle>>> => {
      const _args: string[] = [
      ];
      return this.expectAcceptedTyped("get_triangle", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "geo.aleo", "get_triangle", 0), tpk, "geo.aleo", "get_triangle", 0, (_p: string) => deserializeTriangle(_p)));
    },

    rejected: async (options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.expectRejected("get_triangle", _args, options ?? {});
    },
  } as const;

  readonly get_line = {
    locally: async (args: { readonly triangle: TriangleInput }, options?: LocalExecutionOptions): Promise<Line> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      const _result = await this.executeLocal("get_line", _args, options ?? {});
      return deserializeLine(this.outputAt(_result, "get_line", 0));
    },

    failsLocally: async (args: { readonly triangle: TriangleInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      await this.expectLocalFailure("get_line", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly triangle: TriangleInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      return this.expectLocalFailure("get_line", _args, options ?? {});
    },

    submitted: async (args: { readonly triangle: TriangleInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      return this.submitTransition("get_line", _args, options ?? {});
    },

    settled: async (args: { readonly triangle: TriangleInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Line>> | RejectedTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      return this.settleTyped("get_line", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "geo.aleo", "get_line", 0), tpk, "geo.aleo", "get_line", 1, (_p: string) => deserializeLine(_p)));
    },

    accepted: async (args: { readonly triangle: TriangleInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Line>>> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      return this.expectAcceptedTyped("get_line", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "geo.aleo", "get_line", 0), tpk, "geo.aleo", "get_line", 1, (_p: string) => deserializeLine(_p)));
    },

    rejected: async (args: { readonly triangle: TriangleInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeTriangle(args.triangle as TriangleInput, this.inputContext("get_line", "triangle")),
      ];
      return this.expectRejected("get_line", _args, options ?? {});
    },
  } as const;
}

export function createGeo(options?: BaseContractOptions): Geo {
  return new Geo(options);
}
