// Auto-generated by @lionden/leo-compiler — do not edit
// Program: config.aleo

import { BaseContract, createRecordOutputMatcher, type AcceptedTransition, type AddressInput, type BaseContractOptions, type CapturedRecord, type ConfirmedTransitionRecord, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type IdOnlyDynamicRecordHandle, type IdOnlyExternalRecordHandle, type IdOnlyRecordSource, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RawTransitionOutput, type RecordDecryptionKey, type RecordOutputMatcher, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Inner {
  readonly x: number;
}

export interface InnerInput {
  readonly x: number;
}

export interface Settings {
  readonly admin: LeoAddress;
  readonly backup: LeoAddress | null;
  readonly inner: Inner | null;
}

export interface SettingsInput {
  readonly admin: AddressInput;
  readonly backup: AddressInput | null;
  readonly inner: InnerInput | null;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeInner(value: InnerInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("x: " + BaseContract.serializeUInt(value.x, 32, BaseContract.childInputContext(context, "x")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeInner(value: string): Inner {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
  };
}

export function serializeSettings(value: SettingsInput, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("admin: " + BaseContract.serializeAddress(value.admin, BaseContract.childInputContext(context, "admin")));
  fields.push("backup: " + (value.backup != null ? "{ is_some: true, val: " + BaseContract.serializeAddress(value.backup, BaseContract.childInputContext(context, "backup")) + " }" : "{ is_some: false, val: aleo1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3ljyzc }"));
  fields.push("inner: " + (value.inner != null ? "{ is_some: true, val: " + serializeInner(value.inner as InnerInput, BaseContract.childInputContext(context, "inner")) + " }" : "{ is_some: false, val: { x: 0u32 } }"));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeSettings(value: string): Settings {
  const _fields = BaseContract.parseStruct(value);
  return {
    admin: BaseContract.parseAddress(_fields["admin"]!),
    backup: (() => { const _opt = BaseContract.parseStruct(_fields["backup"]!); return BaseContract.parseBoolean(_opt["is_some"]!) ? BaseContract.parseAddress(_opt["val"]!) : null; })(),
    inner: (() => { const _opt = BaseContract.parseStruct(_fields["inner"]!); return BaseContract.parseBoolean(_opt["is_some"]!) ? deserializeInner(_opt["val"]!) : null; })(),
  };
}

// ---------------------------------------------------------------------------
// Config contract wrapper
// ---------------------------------------------------------------------------

export class Config extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("config.aleo", options);
  }

  readonly get_settings = {
    locally: async (options?: LocalExecutionOptions): Promise<Settings> => {
      const _args: string[] = [
      ];
      const _result = await this.executeLocal("get_settings", _args, options ?? {});
      return deserializeSettings(this.outputAt(_result, "get_settings", 0));
    },

    failsLocally: async (options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
      ];
      await this.expectLocalFailure("get_settings", _args, options ?? {});
    },

    captureLocalFailure: async (options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
      ];
      return this.expectLocalFailure("get_settings", _args, options ?? {});
    },

    submitted: async (options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
      ];
      return this.submitTransition("get_settings", _args, options ?? {});
    },

    settled: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Settings>> | RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.settleTyped("get_settings", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "config.aleo", "get_settings", 0), tpk, "config.aleo", "get_settings", 0, (_p: string) => deserializeSettings(_p)));
    },

    accepted: async (options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedValue<Settings>>> => {
      const _args: string[] = [
      ];
      return this.expectAcceptedTyped("get_settings", _args, options ?? {}, (rawOutputs: readonly RawTransitionOutput[], tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => BaseContract.makeEncryptedValue(BaseContract.rawOutputAt(rawOutputs, "config.aleo", "get_settings", 0), tpk, "config.aleo", "get_settings", 0, (_p: string) => deserializeSettings(_p)));
    },

    rejected: async (options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
      ];
      return this.expectRejected("get_settings", _args, options ?? {});
    },
  } as const;

  readonly update = {
    locally: async (settings: SettingsInput, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      const _result = await this.executeLocal("update", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (settings: SettingsInput, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      await this.expectLocalFailure("update", _args, options ?? {});
    },

    captureLocalFailure: async (settings: SettingsInput, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      return this.expectLocalFailure("update", _args, options ?? {});
    },

    submitted: async (settings: SettingsInput, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      return this.submitTransition("update", _args, options ?? {});
    },

    settled: async (settings: SettingsInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      return this.settleTyped("update", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => undefined as void);
    },

    accepted: async (settings: SettingsInput, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      return this.expectAcceptedTyped("update", _args, options ?? {}, (_rawOutputs: readonly RawTransitionOutput[], _tpk: string, _transitions: readonly ConfirmedTransitionRecord[]) => undefined as void);
    },

    rejected: async (settings: SettingsInput, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeSettings(settings as SettingsInput, this.inputContext("update", "settings")),
      ];
      return this.expectRejected("update", _args, options ?? {});
    },
  } as const;
}

export function createConfig(options?: BaseContractOptions): Config {
  return new Config(options);
}
