// Auto-generated by @lionden/leo-compiler — do not edit
// Program: config.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

export interface Inner {
  readonly x: number;
}

export interface Settings {
  readonly admin: string;
  readonly backup: string | null;
  readonly inner: Inner | null;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeInner(value: Inner): string {
  const fields: string[] = [];
  fields.push("x: " + value.x.toString() + "u32");
  return "{ " + fields.join(", ") + " }";
}

export function deserializeInner(value: string): Inner {
  const _fields = BaseContract.parseStruct(value);
  return {
    x: BaseContract.parseNumber(_fields["x"]!),
  };
}

export function serializeSettings(value: Settings): string {
  const fields: string[] = [];
  fields.push("admin: " + value.admin);
  fields.push("backup: " + (value.backup != null ? "{ is_some: true, val: " + value.backup + " }" : "{ is_some: false, val: aleo1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq3ljyzc }"));
  fields.push("inner: " + (value.inner != null ? "{ is_some: true, val: " + serializeInner(value.inner) + " }" : "{ is_some: false, val: { x: 0u32 } }"));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeSettings(value: string): Settings {
  const _fields = BaseContract.parseStruct(value);
  return {
    admin: BaseContract.parseString(_fields["admin"]!),
    backup: (() => { const _opt = BaseContract.parseStruct(_fields["backup"]!); return BaseContract.parseBoolean(_opt["is_some"]!) ? BaseContract.parseString(_opt["val"]!) : null; })(),
    inner: (() => { const _opt = BaseContract.parseStruct(_fields["inner"]!); return BaseContract.parseBoolean(_opt["is_some"]!) ? deserializeInner(_opt["val"]!) : null; })(),
  };
}

// ---------------------------------------------------------------------------
// Config contract wrapper
// ---------------------------------------------------------------------------

export class Config extends BaseContract {
  constructor() {
    super("config.aleo");
  }

  async get_settings(
    options?: LocalCallOptions,
  ): Promise<Settings> {
    const _args: string[] = [
    ];
    const _result = await this.executeLocal("get_settings", _args, options ?? {});
    return deserializeSettings(_result.outputs[0]!);
  }

  async get_settingsBroadcast(
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
    ];
    return this.broadcast("get_settings", _args, options ?? {});
  }

  async update(
    settings: Settings,
    options?: LocalCallOptions,
  ): Promise<void> {
    const _args: string[] = [
      serializeSettings(settings),
    ];
    const _result = await this.executeLocal("update", _args, options ?? {});
  }

  async updateBroadcast(
    settings: Settings,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      serializeSettings(settings),
    ];
    return this.broadcast("update", _args, options ?? {});
  }
}

export function createConfig(): Config {
  return new Config();
}
