// Auto-generated by @lionden/leo-compiler — do not edit
// Program: rewards.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// Rewards contract wrapper
// ---------------------------------------------------------------------------

export class Rewards extends BaseContract {
  constructor() {
    super("rewards.aleo");
  }

  readonly earn_points = {
    locally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      const _result = await this.executeLocal("earn_points", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      await this.expectLocalFailure("earn_points", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      return this.expectLocalFailure("earn_points", _args, options ?? {});
    },

    submitted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      return this.submitTransition("earn_points", _args, options ?? {});
    },

    settled: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      return this.settleTyped("earn_points", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      return this.expectAcceptedTyped("earn_points", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("earn_points", "amount")),
      ];
      return this.expectRejected("earn_points", _args, options ?? {});
    },
  } as const;

  readonly claim_reward = {
    locally: async (args: { readonly reward_amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      const _result = await this.executeLocal("claim_reward", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly reward_amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      await this.expectLocalFailure("claim_reward", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly reward_amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      return this.expectLocalFailure("claim_reward", _args, options ?? {});
    },

    submitted: async (args: { readonly reward_amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      return this.submitTransition("claim_reward", _args, options ?? {});
    },

    settled: async (args: { readonly reward_amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      return this.settleTyped("claim_reward", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly reward_amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      return this.expectAcceptedTyped("claim_reward", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly reward_amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.reward_amount, 64, this.inputContext("claim_reward", "reward_amount")),
      ];
      return this.expectRejected("claim_reward", _args, options ?? {});
    },
  } as const;

  async getPoints(key: AddressInput): Promise<bigint | null> {
    const _result = await this.queryMapping("points", BaseContract.serializeAddress(key, { programId: this.programId, input: "points key" }));
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }

  async getClaimed(key: AddressInput): Promise<boolean | null> {
    const _result = await this.queryMapping("claimed", BaseContract.serializeAddress(key, { programId: this.programId, input: "claimed key" }));
    if (_result === null) return null;
    return BaseContract.parseBoolean(_result);
  }
}

export function createRewards(): Rewards {
  return new Rewards();
}
