// Auto-generated by @lionden/leo-compiler — do not edit
// Program: vault.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type BaseContractOptions, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Policy {
  readonly max_amount: bigint;
  readonly admin: LeoAddress;
}

export interface VaultStorage {
  readonly admin: LeoAddress;
  readonly whitelist: LeoAddress[];
  readonly policy: Policy;
  readonly policies: Policy[];
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializePolicy(value: Policy, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const fields: string[] = [];
  fields.push("max_amount: " + BaseContract.serializeUInt(value.max_amount, 128, BaseContract.childInputContext(context, "max_amount")));
  fields.push("admin: " + BaseContract.serializeAddress(value.admin, BaseContract.childInputContext(context, "admin")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializePolicy(value: string): Policy {
  const _fields = BaseContract.parseStruct(value);
  return {
    max_amount: BaseContract.parseBigInt(_fields["max_amount"]!),
    admin: BaseContract.parseAddress(_fields["admin"]!),
  };
}

// ---------------------------------------------------------------------------
// Vault contract wrapper
// ---------------------------------------------------------------------------

export class Vault extends BaseContract {
  constructor(options?: BaseContractOptions) {
    super("vault.aleo", options);
  }

  readonly set_admin = {
    locally: async (args: { readonly new_admin: AddressInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      const _result = await this.executeLocal("set_admin", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly new_admin: AddressInput }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      await this.expectLocalFailure("set_admin", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly new_admin: AddressInput }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      return this.expectLocalFailure("set_admin", _args, options ?? {});
    },

    submitted: async (args: { readonly new_admin: AddressInput }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      return this.submitTransition("set_admin", _args, options ?? {});
    },

    settled: async (args: { readonly new_admin: AddressInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      return this.settleTyped("set_admin", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly new_admin: AddressInput }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      return this.expectAcceptedTyped("set_admin", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly new_admin: AddressInput }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.new_admin, this.inputContext("set_admin", "new_admin")),
      ];
      return this.expectRejected("set_admin", _args, options ?? {});
    },
  } as const;
}

export function createVault(options?: BaseContractOptions): Vault {
  return new Vault(options);
}
