// Auto-generated by @lionden/leo-compiler — do not edit
// Program: token.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

export interface Token {
  readonly owner: LeoAddress;
  readonly amount: bigint;
  readonly _nonce: LeoGroup;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeToken(value: Token, context?: TransitionInputContext): string {
  BaseContract.assertObject(value, context);
  const _raw = (value as unknown as { readonly [k: symbol]: unknown })[BaseContract.RECORD_RAW];
  if (typeof _raw === "string") return _raw;
  const fields: string[] = [];
  fields.push("owner: " + BaseContract.serializeAddress(value.owner, BaseContract.childInputContext(context, "owner")));
  fields.push("amount: " + BaseContract.serializeUInt(value.amount, 64, BaseContract.childInputContext(context, "amount")));
  fields.push("_nonce: " + BaseContract.serializeGroup(value._nonce, BaseContract.childInputContext(context, "_nonce")));
  return "{ " + fields.join(", ") + " }";
}

export function deserializeToken(value: string): Token {
  const _fields = BaseContract.parseStruct(value);
  const _record: Token = {
    owner: BaseContract.parseAddress(_fields["owner"]!),
    amount: BaseContract.parseBigInt(_fields["amount"]!),
    _nonce: BaseContract.parseGroup(_fields["_nonce"] ?? ""),
  };
  Object.defineProperty(_record, BaseContract.RECORD_RAW, { value, enumerable: false });
  return _record;
}

export async function decryptToken(ciphertext: string, key: RecordDecryptionKey): Promise<Token> {
  return BaseContract.decryptRecord(ciphertext, key, deserializeToken);
}

// ---------------------------------------------------------------------------
// TokenContract contract wrapper
// ---------------------------------------------------------------------------

export class TokenContract extends BaseContract {
  constructor() {
    super("token.aleo");
  }

  readonly mint_public = {
    locally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      const _result = await this.executeLocal("mint_public", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      await this.expectLocalFailure("mint_public", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      return this.expectLocalFailure("mint_public", _args, options ?? {});
    },

    submitted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      return this.submitTransition("mint_public", _args, options ?? {});
    },

    settled: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      return this.settleTyped("mint_public", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      return this.expectAcceptedTyped("mint_public", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_public", "amount")),
      ];
      return this.expectRejected("mint_public", _args, options ?? {});
    },
  } as const;

  readonly transfer_public = {
    locally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      const _result = await this.executeLocal("transfer_public", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      await this.expectLocalFailure("transfer_public", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      return this.expectLocalFailure("transfer_public", _args, options ?? {});
    },

    submitted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      return this.submitTransition("transfer_public", _args, options ?? {});
    },

    settled: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      return this.settleTyped("transfer_public", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      return this.expectAcceptedTyped("transfer_public", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_public", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_public", "amount")),
      ];
      return this.expectRejected("transfer_public", _args, options ?? {});
    },
  } as const;

  readonly mint_private = {
    locally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<Token> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      const _result = await this.executeLocal("mint_private", _args, options ?? {});
      return deserializeToken(this.outputAt(_result, "mint_private", 0));
    },

    failsLocally: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      await this.expectLocalFailure("mint_private", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      return this.expectLocalFailure("mint_private", _args, options ?? {});
    },

    submitted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      return this.submitTransition("mint_private", _args, options ?? {});
    },

    settled: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      return this.settleTyped("mint_private", _args, options ?? {}, (rawOutputs: readonly string[], _tpk: string) => BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "mint_private", 0), deserializeToken));
    },

    accepted: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<EncryptedRecord<Token>>> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      return this.expectAcceptedTyped("mint_private", _args, options ?? {}, (rawOutputs: readonly string[], _tpk: string) => BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "mint_private", 0), deserializeToken));
    },

    rejected: async (args: { readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeAddress(args.receiver, this.inputContext("mint_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("mint_private", "amount")),
      ];
      return this.expectRejected("mint_private", _args, options ?? {});
    },
  } as const;

  readonly transfer_private = {
    locally: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<[Token, Token]> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      const _result = await this.executeLocal("transfer_private", _args, options ?? {});
      const _decoded: [Token, Token] = [deserializeToken(this.outputAt(_result, "transfer_private", 0)), deserializeToken(this.outputAt(_result, "transfer_private", 1))];
      return _decoded;
    },

    failsLocally: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      await this.expectLocalFailure("transfer_private", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      return this.expectLocalFailure("transfer_private", _args, options ?? {});
    },

    submitted: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      return this.submitTransition("transfer_private", _args, options ?? {});
    },

    settled: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<[EncryptedRecord<Token>, EncryptedRecord<Token>]> | RejectedTransition> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      return this.settleTyped("transfer_private", _args, options ?? {}, (rawOutputs: readonly string[], _tpk: string) => ([BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "transfer_private", 0), deserializeToken), BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "transfer_private", 1), deserializeToken)] as [EncryptedRecord<Token>, EncryptedRecord<Token>]));
    },

    accepted: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<[EncryptedRecord<Token>, EncryptedRecord<Token>]>> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      return this.expectAcceptedTyped("transfer_private", _args, options ?? {}, (rawOutputs: readonly string[], _tpk: string) => ([BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "transfer_private", 0), deserializeToken), BaseContract.makeEncryptedRecord(BaseContract.rawOutputAt(rawOutputs, "token.aleo", "transfer_private", 1), deserializeToken)] as [EncryptedRecord<Token>, EncryptedRecord<Token>]));
    },

    rejected: async (args: { readonly token: Token; readonly receiver: AddressInput; readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        serializeToken(args.token as Token, this.inputContext("transfer_private", "token")),
        BaseContract.serializeAddress(args.receiver, this.inputContext("transfer_private", "receiver")),
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("transfer_private", "amount")),
      ];
      return this.expectRejected("transfer_private", _args, options ?? {});
    },
  } as const;

  async getBalances(key: AddressInput): Promise<bigint | null> {
    const _result = await this.queryMapping("balances", BaseContract.serializeAddress(key, { programId: this.programId, input: "balances key" }));
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }
}

export function createTokenContract(): TokenContract {
  return new TokenContract();
}
