// Auto-generated by @lionden/leo-compiler — do not edit
// Program: token.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

export interface Token {
  readonly owner: string;
  readonly amount: bigint;
  readonly _nonce: string;
}

// ---------------------------------------------------------------------------
// Serialization / deserialization helpers
// ---------------------------------------------------------------------------

export function serializeToken(value: Token): string {
  const fields: string[] = [];
  fields.push("owner: " + value.owner);
  fields.push("amount: " + value.amount.toString() + "u64");
  fields.push("_nonce: " + value._nonce);
  return "{ " + fields.join(", ") + " }";
}

export function deserializeToken(value: string): Token {
  const _fields = BaseContract.parseStruct(value);
  return {
    owner: BaseContract.parseString(_fields["owner"]!),
    amount: BaseContract.parseBigInt(_fields["amount"]!),
    _nonce: BaseContract.parseString(_fields["_nonce"] ?? ""),
  };
}

// ---------------------------------------------------------------------------
// TokenContract contract wrapper
// ---------------------------------------------------------------------------

export class TokenContract extends BaseContract {
  constructor() {
    super("token.aleo");
  }

  async mint_public(
    receiver: string,
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<void> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("mint_public", _args, options ?? {});
    return undefined as any;
  }

  async mint_publicBroadcast(
    receiver: string,
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    return this.broadcast("mint_public", _args, options ?? {});
  }

  async transfer_public(
    receiver: string,
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<void> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("transfer_public", _args, options ?? {});
    return undefined as any;
  }

  async transfer_publicBroadcast(
    receiver: string,
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    return this.broadcast("transfer_public", _args, options ?? {});
  }

  async mint_private(
    receiver: string,
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<Token> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("mint_private", _args, options ?? {});
    return deserializeToken(_result.outputs[0]!);
  }

  async mint_privateBroadcast(
    receiver: string,
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      receiver,
      amount.toString() + "u64",
    ];
    return this.broadcast("mint_private", _args, options ?? {});
  }

  async transfer_private(
    token: Token,
    receiver: string,
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<[Token, Token]> {
    const _args: string[] = [
      serializeToken(token),
      receiver,
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("transfer_private", _args, options ?? {});
    const _decoded: [Token, Token] = [deserializeToken(_result.outputs[0]!), deserializeToken(_result.outputs[1]!)];
    return _decoded;
  }

  async transfer_privateBroadcast(
    token: Token,
    receiver: string,
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      serializeToken(token),
      receiver,
      amount.toString() + "u64",
    ];
    return this.broadcast("transfer_private", _args, options ?? {});
  }

  async getBalances(key: string): Promise<bigint | null> {
    const _result = await this.queryMapping("balances", key);
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }
}

export function createTokenContract(): TokenContract {
  return new TokenContract();
}
