// Auto-generated by @lionden/leo-compiler — do not edit
// Program: treasury.aleo

import { BaseContract, type AcceptedTransition, type AddressInput, type DecryptionKey, type DynamicRecordInput, type EncryptedRecord, type EncryptedValue, type FieldInput, type GroupInput, type IdentifierInput, type LeoAddress, type LeoDynamicRecord, type LeoField, type LeoGroup, type LeoIdentifier, type LeoPlaintext, type LeoScalar, type LocalExecutionOptions, type LocalTransitionError, type OnChainExecutionOptions, type PlaintextInput, type RecordDecryptionKey, type RejectedTransition, type ScalarInput, type SettledTransition, type SubmittedTransition, type TransitionInputContext } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// Treasury contract wrapper
// ---------------------------------------------------------------------------

export class Treasury extends BaseContract {
  constructor() {
    super("treasury.aleo");
  }

  readonly deposit = {
    locally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      const _result = await this.executeLocal("deposit", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      await this.expectLocalFailure("deposit", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      return this.expectLocalFailure("deposit", _args, options ?? {});
    },

    submitted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      return this.submitTransition("deposit", _args, options ?? {});
    },

    settled: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      return this.settleTyped("deposit", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      return this.expectAcceptedTyped("deposit", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("deposit", "amount")),
      ];
      return this.expectRejected("deposit", _args, options ?? {});
    },
  } as const;

  readonly withdraw = {
    locally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      const _result = await this.executeLocal("withdraw", _args, options ?? {});
      return undefined as any;
    },

    failsLocally: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<void> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      await this.expectLocalFailure("withdraw", _args, options ?? {});
    },

    captureLocalFailure: async (args: { readonly amount: bigint }, options?: LocalExecutionOptions): Promise<LocalTransitionError> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      return this.expectLocalFailure("withdraw", _args, options ?? {});
    },

    submitted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<SubmittedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      return this.submitTransition("withdraw", _args, options ?? {});
    },

    settled: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void> | RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      return this.settleTyped("withdraw", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    accepted: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<AcceptedTransition<void>> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      return this.expectAcceptedTyped("withdraw", _args, options ?? {}, (_rawOutputs: readonly string[], _tpk: string) => undefined as void);
    },

    rejected: async (args: { readonly amount: bigint }, options?: OnChainExecutionOptions): Promise<RejectedTransition> => {
      const _args: string[] = [
        BaseContract.serializeUInt(args.amount, 64, this.inputContext("withdraw", "amount")),
      ];
      return this.expectRejected("withdraw", _args, options ?? {});
    },
  } as const;

  async getDeposits(key: AddressInput): Promise<bigint | null> {
    const _result = await this.queryMapping("deposits", BaseContract.serializeAddress(key, { programId: this.programId, input: "deposits key" }));
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }
}

export function createTreasury(): Treasury {
  return new Treasury();
}
