// Auto-generated by @lionden/leo-compiler — do not edit
// Program: treasury.aleo

import { BaseContract, type LocalCallOptions, type BroadcastOptions, type TransitionCallResult } from "./BaseContract.js";

// ---------------------------------------------------------------------------
// Treasury contract wrapper
// ---------------------------------------------------------------------------

export class Treasury extends BaseContract {
  constructor() {
    super("treasury.aleo");
  }

  async deposit(
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<void> {
    const _args: string[] = [
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("deposit", _args, options ?? {});
    return undefined as any;
  }

  async depositBroadcast(
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      amount.toString() + "u64",
    ];
    return this.broadcast("deposit", _args, options ?? {});
  }

  async withdraw(
    amount: bigint,
    options?: LocalCallOptions,
  ): Promise<void> {
    const _args: string[] = [
      amount.toString() + "u64",
    ];
    const _result = await this.executeLocal("withdraw", _args, options ?? {});
    return undefined as any;
  }

  async withdrawBroadcast(
    amount: bigint,
    options?: BroadcastOptions,
  ): Promise<TransitionCallResult> {
    const _args: string[] = [
      amount.toString() + "u64",
    ];
    return this.broadcast("withdraw", _args, options ?? {});
  }

  async getDeposits(key: string): Promise<bigint | null> {
    const _result = await this.queryMapping("deposits", key);
    if (_result === null) return null;
    return BaseContract.parseBigInt(_result);
  }
}

export function createTreasury(): Treasury {
  return new Treasury();
}
